== Configuration-Setting Instructions (`vsetvli`/`vsetivli`/`vsetvl`)

////
 31 30         25 24      20 19      15 14   12 11      7 6     0
 0 |        zimm[10:0]      |    rs1   | 1 1 1 |    rd   |1010111| vsetvli
 1 |   1|  zimm[ 9:0]       | uimm[4:0]| 1 1 1 |    rd   |1010111| vsetivli
 1 |   000000    |   rs2    |    rs1   | 1 1 1 |    rd   |1010111| vsetvl
 1        6            5          5        3        5        7
////


=== vsetvli

Mnemonic::
--
    vsetvli rd, rs1, vtypei
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7,  name: 0x57, attr: 'vsetvli'},
  {bits: 5,  name: 'rd', type: 4},
  {bits: 3,  name: 7},
  {bits: 5,  name: 'rs1', type: 4},
  {bits: 11, name: 'vtypei[10:0]', type: 5},
  {bits: 1,  name: '0'},
]}
....

Description::
rd = new vl, rs1 = AVL, vtypei = new vtype setting



=== vsetivli

Mnemonic::
--
    vsetivli rd, uimm, vtypei
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7,  name: 0x57, attr: 'vsetivli'},
  {bits: 5,  name: 'rd', type: 4},
  {bits: 3,  name: 7},
  {bits: 5,  name: 'uimm[4:0]', type: 5},
  {bits: 10, name: 'vtypei[9:0]', type: 5},
  {bits: 1, name: '1'},
  {bits: 1,  name: '1'},
]}
....

Description::
rd = new vl, uimm = AVL, vtypei = new vtype setting


=== vsetvl

Mnemonic::
--
    vsetvl  rd, rs1, rs2
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7,  name: 0x57, attr: 'vsetvl'},
  {bits: 5,  name: 'rd', type: 4},
  {bits: 3,  name: 7},
  {bits: 5,  name: 'rs1', type: 4},
  {bits: 5,  name: 'rs2', type: 4},
  {bits: 6,  name: 0x00},
  {bits: 1,  name: 1},
]}
....

Description::
rd = new vl, rs1 = AVL, rs2 = new vtype value
