== Vector Single-Width Integer Add and Subtract

=== vadd.vv

Mnemonic::
--
    vadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0, attr: 'funct6'},
]}
....

Descrption::
Integer addition, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadd_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadd_vv_intrinsic.cpp[]
----
====

=== vadd.vx
Mnemonic::
--
    vadd.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0, attr: 'funct6'},
]}
....

Descrption::
Integer addition, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadd_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadd_vx_intrinsic.cpp[]
----
====
=== vadd.vi

Mnemonic::
--
    vadd.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0, attr: 'funct6'},
]}
....

Descrption::
Integer addition, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadd_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadd_vi_intrinsic.cpp[]
----
====

=== vsub.vv
Mnemonic::
--
    vsub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 2, attr: 'funct6'},
]}
....


Description::
Integer subtraction, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsub_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsub_vv_intrinsic.cpp[]
----
====

=== vsub.vx

Mnemonic::
--
    vsub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 2, attr: 'funct6'},
]}
....

Description::
Integer subtraction, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsub_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsub_vx_intrinsic.cpp[]
----
====

=== vrsub.vx

Mnemonic::
--
    vrsub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 3, attr: 'funct6'},
]}
....

Description::
Integer reverse subtract, vd[i] = x[rs1] - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrsub_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vrsub_vx_intrinsic.cpp[]
----
====

=== vrsub.vi

Mnemonic::
--
    vrsub.vi vd, vs2, imm, vm
--

Encoding::

[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 3, attr: 'funct6'},
]}
....

Description::
Integer reverse subtract, vd[i] = imm - vs2[i]


== Vector Widening Integer Add/Subtract

The widening add/subtract instructions are provided in both signed and
unsigned variants, depending on whether the narrower source operands
are first sign- or zero-extended before forming the double-width sum.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrsub_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vrsub_vi_intrinsic.cpp[]
----
====

=== vwaddu.vv

Mnemonic::
--
  vwaddu.vv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x30, attr: 'funct6'},
]}
....


Description::
Widening unsigned integer add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwaddu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwaddu_vv_intrinsic.cpp[]
----
====

=== vwaddu.vx

Mnemonic::
--
  vwaddu.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x30, attr: 'funct6'},
]}
....

Description::
Widening unsigned integer add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwaddu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwaddu_vx_intrinsic.cpp[]
----
====

=== vwsubu.vv

Mnemonic::
--
  vwsubu.vv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x32, attr: 'funct6'},
]}
....

Description::
Widening unsigned integer add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsubu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsubu_vv_intrinsic.cpp[]
----
====

=== vwsubu.vx

Mnemonic::
--
  vwsubu.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x32, attr: 'funct6'},
]}
....

Description::
Widening unsigned integer add/subtract, 2*SEW = SEW +/- SEW, vector-scalar


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsubu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsubu_vx_intrinsic.cpp[]
----
====

=== vwadd.vv

Mnemonic::
--
  vwadd.vv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x31, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwadd_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwadd_vv_intrinsic.cpp[]
----
====

=== vwadd.vx

Mnemonic::
--
  vwadd.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x31, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwadd_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwadd_vx_intrinsic.cpp[]
----
====

=== vwsub.vv

Mnemonic::
--
  vwsub.vv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x33, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsub_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsub_vv_intrinsic.cpp[]
----
====

=== vwsub.vx

Mnemonic::
--
  vwsub.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x33, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = SEW +/- SEW, vector-scalar


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsub_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsub_vx_intrinsic.cpp[]
----
====

=== vwaddu.wv

Mnemonic::
--
  vwaddu.wv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x34, attr: 'funct6'},
]}
....

Description::
Widening unsigned integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwaddu_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwaddu_wv_intrinsic.cpp[]
----
====

=== vwaddu.wx

Mnemonic::
--
  vwaddu.wx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x34, attr: 'funct6'},
]}
....


Description::
Widening unsigned integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwaddu_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwaddu_wx_intrinsic.cpp[]
----
====

=== vwsubu.wv

Mnemonic::
--
  vwsubu.wv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x36, attr: 'funct6'},
]}
....

Description::
Widening unsigned integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsubu_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsubu_wv_intrinsic.cpp[]
----
====

=== vwsubu.wx

Mnemonic::
--
  vwsubu.wx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x36, attr: 'funct6'},
]}
....


Description::
Widening unsigned integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsubu_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsubu_wx_intrinsic.cpp[]
----
====

=== vwadd.wv

Mnemonic::
--
  vwadd.wv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x35, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwadd_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwadd_wv_intrinsic.cpp[]
----
====

=== vwadd.wx

Mnemonic::
--
  vwadd.wx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x35, attr: 'funct6'},
]}
....


Description::
Widening signed integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwadd_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwadd_wx_intrinsic.cpp[]
----
====

=== vwsub.wv

Mnemonic::
--
  vwsub.wv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x37, attr: 'funct6'},
]}
....

Description::
Widening signed integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsub_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsub_wv_intrinsic.cpp[]
----
====

=== vwsub.wx

Mnemonic::
--
  vwsub.wx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x37, attr: 'funct6'},
]}
....


Description::
Widening signed integer add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

== Vector Integer Extension

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwsub_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwsub_wx_intrinsic.cpp[]
----
====

=== vzext.vf2
Mnemonic::
--
  vzext.vf2 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x6, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Zero-extend SEW/2 source to SEW destination

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vzext_vf2.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vzext_vf2_intrinsic.cpp[]
----
====

=== vsext.vf2
Mnemonic::
--
  vsext.vf2 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x7, attr:'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Sign-extend SEW/2 source to SEW destination

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsext_vf2.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsext_vf2_intrinsic.cpp[]
----
====

=== vzext.vf4
Mnemonic::
--
  vzext.vf4 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x4, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Zero-extend SEW/4 source to SEW destination

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vzext_vf4.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vzext_vf4_intrinsic.cpp[]
----
====

=== vsext.vf4
Mnemonic::
--
  vsext.vf4 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x5, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Sign-extend SEW/4 source to SEW destination

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsext_vf4.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsext_vf4_intrinsic.cpp[]
----
====

=== vzext.vf8
Mnemonic::
--
  vzext.vf8 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x2, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Zero-extend SEW/8 source to SEW destination

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vzext_vf8.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vzext_vf8_intrinsic.cpp[]
----
====

=== vsext.vf8
Mnemonic::
--
  vsext.vf8 vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x3, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Sign-extend SEW/8 source to SEW destination

== Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsext_vf8.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsext_vf8_intrinsic.cpp[]
----
====

=== vadc.vvm

Mnemonic::
--
  vadc.vvm   vd, vs2, vs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x10, attr: 'funct6'},
]}
....

Description::
Produce sum with carry. vd[i] = vs2[i] + vs1[i] + v0.mask[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadc_vvm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadc_vvm_intrinsic.cpp[]
----
====

=== vadc.vxm

Mnemonic::
--
  vadc.vxm   vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x10, attr: 'funct6'},
]}
....

Description::
Produce sum with carry. vd[i] = vs2[i] + x[rs1] + v0.mask[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadc_vxm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadc_vxm_intrinsic.cpp[]
----
====

=== vadc.vim

Mnemonic::
--
  vadc.vim   vd, vs2, imm, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x10, attr: 'funct6'},
]}
....

Description::
Produce sum with carry. vd[i] = vs2[i] + imm + v0.mask[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vadc_vim.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vadc_vim_intrinsic.cpp[]
----
====

=== vmadc.vvm

Mnemonic::
--
  vmadc.vvm   vd, vs2, vs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + vs1[i] + v0.mask[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vvm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vvm_intrinsic.cpp[]
----
====

=== vmadc.vxm

Mnemonic::
--
  vmadc.vxm   vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + x[rs1] + v0.mask[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vxm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vxm_intrinsic.cpp[]
----
====

=== vmadc.vim

Mnemonic::
--
  vmadc.vim   vd, vs2, imm, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + imm + v0.mask[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vim.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vim_intrinsic.cpp[]
----
====

=== vmadc.vv

Mnemonic::
--
  vmadc.vv    vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + vs1[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vv_intrinsic.cpp[]
----
====

=== vmadc.vx

Mnemonic::
--
  vmadc.vx    vd, vs2, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + x[rs1])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vx_intrinsic.cpp[]
----
====

=== vmadc.vi

Mnemonic::
--
  vmadc.vi    vd, vs2, imm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x11, attr: 'funct6'},
]}
....

Description::
Produce carry out in mask register format. vd.mask[i] = carry_out(vs2[i] + imm)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadc_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadc_vi_intrinsic.cpp[]
----
====

=== vsbc.vvm

Mnemonic::
--
  vsbc.vvm   vd, vs2, vs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Produce difference with borrow. vd[i] = vs2[i] - vs1[i] - v0.mask[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsbc_vvm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsbc_vvm_intrinsic.cpp[]
----
====

=== vsbc.vxm

Mnemonic::
--
  vsbc.vxm   vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Produce difference with borrow. vd[i] = vs2[i] - x[rs1] - v0.mask[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsbc_vxm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsbc_vxm_intrinsic.cpp[]
----
====

=== vmsbc.vvm

Mnemonic::
--
  vmsbc.vvm   vd, vs2, vs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Produce borrow out in mask register format. vd.mask[i] = borrow_out(vs2[i] - vs1[i] - v0.mask[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsbc_vvm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsbc_vvm_intrinsic.cpp[]
----
====

=== vmsbc.vxm

Mnemonic::
--
  vmsbc.vxm   vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x0, attr: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Produce borrow out in mask register format. vd.mask[i] = borrow_out(vs2[i] - x[rs1] - v0.mask[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsbc_vxm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsbc_vxm_intrinsic.cpp[]
----
====

=== vmsbc.vv

Mnemonic::
--
  vmsbc.vv    vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Produce borrow out in mask register format. vd.mask[i] = borrow_out(vs2[i] - vs1[i])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsbc_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsbc_vv_intrinsic.cpp[]
----
====

=== vmsbc.vx

Mnemonic::
--
  vmsbc.vx    vd, vs2, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Produce borrow out in mask register format. vd.mask[i] = borrow_out(vs2[i] - x[rs1])

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsbc_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsbc_vx_intrinsic.cpp[]
----
====
