= Vector Floating-Point Instructions

== Vector Single-Width Floating-Point Add/Subtract Instructions

=== vfadd.vv
Mnemonic::
--
	vfadd.vv vd, vs2, vs1, vm
--

Description::
Floating-point add, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfadd_vv.h[]

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

=== vfadd.vf
Mnemonic::
--
	vfadd.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point add, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfadd_vf.h[]

=== vfsub.vv
Mnemonic::
--
	vfsub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point subtract, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsub_vv.h[]

=== vfsub.vf
Mnemonic::
--
	vfsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point subtract, Vector-scalar vd[i] = vs2[i] - f[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsub_vf.h[]

=== vfrsub.vf
Mnemonic::
--
	vfrsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point subtract, Scalar-vector vd[i] = f[rs1] - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrsub_vf.h[]

== Vector Widening Floating-Point Add/Subtract Instructions



=== vfwadd.vv
Mnemonic::
--
	vfwadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_vv.h[]

=== vfwadd.vf
Mnemonic::
--
	vfwadd.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_vf.h[]

=== vfwsub.vv
Mnemonic::
--
	vfwsub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsb_vv.h[]

=== vfwsub.vf
Mnemonic::
--
	vfwsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_vf.h[]

=== vfwadd.wv
Mnemonic::
--
	vfwadd.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_wv.h[]

=== vfwadd.wf
Mnemonic::
--
	vfwadd.wf vd, vs2, rs1, vm
--

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_wf.h[]

=== vfwsub.wv
Mnemonic::
--
	vfwsub.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_wf.h[]

=== vfwsub.wf
Mnemonic::
--
	vfwsub.wf vd, vs2, rs1, vm
--

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_wf.h[]

== Vector Single-Width Floating-Point Multiply/Divide Instructions



=== vfmul.vv
Mnemonic::
--
	vfmul.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point multiply, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmul_vv.h[]

=== vfmul.vf
Mnemonic::
--
	vfmul.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmul_vf.h[]

=== vfdiv.vv
Mnemonic::
--
	vfdiv.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point divide, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfdiv_vv.h[]

=== vfdiv.vf
Mnemonic::
--
	vfdiv.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point divide, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfdiv_vf.h[]

=== vfrdiv.vf
Mnemonic::
--
	vfrdiv.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Reverse floating-point divide vector = scalar / vector, scalar-vector, vd[i] = f[rs1]/vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrdiv_vf.h[]

== Vector Widening Floating-Point Multiply



=== vfwmul.vv
Mnemonic::
--
	vfwmul.vv    vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening floating-point multiply, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmul_vv.h[]

=== vfwmul.vf
Mnemonic::
--
	vfwmul.vf    vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Widening floating-point multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmul_vf.h[]

== Vector Single-Width Floating-Point Fused Multiply-Add Instructions



=== vfmacc.vv
Mnemonic::
--
	vfmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-accumulate, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmacc_vv.h[]

=== vfmacc.vf
Mnemonic::
--
	vfmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-accumulate, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmacc_vf.h[]

=== vfnmacc.vv
Mnemonic::
--
	vfnmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-accumulate), overwrites subtrahend, vd[i] = -(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmacc_vv.h[]

=== vfnmacc.vf
Mnemonic::
--
	vfnmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-accumulate), overwrites subtrahend, vd[i] = -(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmacc_vf.h[]

=== vfmsac.vv
Mnemonic::
--
	vfmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-subtract-accumulator, overwrites subtrahend, vd[i] = +(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsac_vv.h[]

=== vfmsac.vf
Mnemonic::
--
	vfmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-subtract-accumulator, overwrites subtrahend, vd[i] = +(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsac_vf.h[]

=== vfnmsac.vv
Mnemonic::
--
	vfnmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-subtract-accumulator), overwrites minuend, vd[i] = -(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsac_vv.h[]

=== vfnmsac.vf
Mnemonic::
--
	vfnmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-subtract-accumulator), overwrites minuend, vd[i] = -(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsac_vf.h[]

=== vfmadd.vv
Mnemonic::
--
	vfmadd.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-add, overwrites multiplicand, vd[i] = +(vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmadd_vv.h[]

=== vfmadd.vf
Mnemonic::
--
	vfmadd.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-add, overwrites multiplicand, vd[i] = +(f[rs1] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmadd_vf.h[]

=== vfnmadd.vv
Mnemonic::
--
	vfnmadd.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-add), overwrites multiplicand, vd[i] = -(vs1[i] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmadd_vv.h[]

=== vfnmadd.vf
Mnemonic::
--
	vfnmadd.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-add), overwrites multiplicand, vd[i] = -(f[rs1] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmadd_vf.h[]

=== vfmsub.vv
Mnemonic::
--
	vfmsub.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-sub, overwrites multiplicand, vd[i] = +(vs1[i] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsub_vv.h[]

=== vfmsub.vf
Mnemonic::
--
	vfmsub.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP multiply-sub, overwrites multiplicand, vd[i] = +(f[rs1] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsub_vf.h[]

=== vfnmsub.vv
Mnemonic::
--
	vfnmsub.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-sub), overwrites multiplicand, vd[i] = -(vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsub_vv.h[]

=== vfnmsub.vf
Mnemonic::
--
	vfnmsub.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP negate-(multiply-sub), overwrites multiplicand, vd[i] = -(f[rs1] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsub_vf.h[]

== Vector Widening Floating-Point Fused Multiply-Add Instructions



=== vfwmacc.vv
Mnemonic::
--
	vfwmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening multiply-accumulate, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmacc_vv.h[]

=== vfwmacc.vf
Mnemonic::
--
	vfwmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening multiply-accumulate, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmacc_vf.h[]

=== vfwnmacc.vv
Mnemonic::
--
	vfwnmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-accumulate), overwrites addend, vd[i] = -(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmacc_vv.h[]

=== vfwnmacc.vf
Mnemonic::
--
	vfwnmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-accumulate), overwrites addend, vd[i] = -(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmacc_vf.h[]

=== vfwmsac.vv
Mnemonic::
--
	vfwmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening multiply-subtract-accumulator, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmsac_vv.h[]

=== vfwmsac.vf
Mnemonic::
--
	vfwmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening multiply-subtract-accumulator, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmsac_vf.h[]

=== vfwnmsac.vv
Mnemonic::
--
	vfwnmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-subtract-accumulator), overwrites addend, vd[i] = -(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmsac_vv.h[]

=== vfwnmsac.vf
Mnemonic::
--
	vfwnmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-subtract-accumulator), overwrites addend, vd[i] = -(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmsac_vf.h[]

== Vector Floating-Point Square-Root Instruction



=== vfsqrt.v
Mnemonic::
--
	vfsqrt.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point square root, Vector-vector square root

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsqrt_v.h[]

== Vector Floating-Point Reciprocal Square-Root Estimate Instruction



=== vfrsqrt7.v
Mnemonic::
--
	vfrsqrt7.v vd, vs2, vm
--

Description::
Floating-point reciprocal square-root estimate to 7 bits.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrsqrt7_v.h[]

== Vector Floating-Point Reciprocal Estimate Instruction



=== vfrec7.v
Mnemonic::
--
	vfrec7.v vd, vs2, vm
--

Description::
Floating-point reciprocal estimate to 7 bits.

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrec7_v.h[]

== Vector Floating-Point MIN/MAX Instructions



=== vfmin.vv
Mnemonic::
--
	vfmin.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point minimum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmin_vv.h[]

=== vfmin.vf
Mnemonic::
--
	vfmin.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmin_vf.h[]

Description::
Floating-point minimum, vector-scalar

=== vfmax.vv
Mnemonic::
--
	vfmax.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point maximum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmax_vv.h[]

=== vfmax.vf
Mnemonic::
--
	vfmax.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point maximum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmax_vf.h[]

== Vector Floating-Point Sign-Injection Instructions



=== vfsgnj.vv
Mnemonic::
--
	vfsgnj.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnj_vv.h[]

=== vfsgnj.vf
Mnemonic::
--
	vfsgnj.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnj_vf.h[]

=== vfsgnjn.vv
Mnemonic::
--
	vfsgnjn.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjn_vv.h[]

=== vfsgnjn.vf
Mnemonic::
--
	vfsgnjn.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjn_vf.h[]

=== vfsgnjx.vv
Mnemonic::
--
	vfsgnjx.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjx_vv.h[]

=== vfsgnjx.vf
Mnemonic::
--
	vfsgnjx.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjx_vf.h[]

== Vector Floating-Point Compare Instructions



=== vmfeq.vv
Mnemonic::
--
	vmfeq.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfeq_vv.h[]

=== vmfeq.vf
Mnemonic::
--
	vmfeq.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmeq_vf.h[]

=== vmfne.vv
Mnemonic::
--
	vmfne.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare not equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfne_vv.h[]

=== vmfne.vf
Mnemonic::
--
	vmfne.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare not equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfne_vf.h[]

=== vmflt.vv
Mnemonic::
--
	vmflt.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare less than, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmflt_vv.h[]

=== vmflt.vf
Mnemonic::
--
	vmflt.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare less than, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmflt_vf.h[]

=== vmfle.vv
Mnemonic::
--
	vmfle.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare less than or equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfle_vv.h[]

=== vmfle.vf
Mnemonic::
--
	vmfle.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare less than or equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfle_vf.h[]

=== vmfgt.vf
Mnemonic::
--
	vmfgt.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare greater than, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfgt_vf.h[]

=== vmfge.vf
Mnemonic::
--
	vmfge.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Compare greater than or equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfge_vf.h[]

== Vector Floating-Point Classify Instruction



=== vfclass.v
Mnemonic::
--
	vfclass.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfclass_v.h[]

== Vector Floating-Point Merge Instruction



=== vfmerge.vfm
Mnemonic::
--
	vfmerge.vfm vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
vd[i] = v0.mask[i] ? f[rs1] : vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmerge_vfm.h[]

== Vector Floating-Point Move Instruction

=== vfmv.v.f
Mnemonic::
--
	vfmv.v.f vd, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
vd[i] = f[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmv_v_f.h[]

== Single-Width Floating-Point/Integer Type-Convert Instructions

=== vfcvt.xu.f.v
Mnemonic::
--
	vfcvt.xu.f.v     vd, vs2, vm
--

Description::
Convert float to unsigned integer.

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_xu_f_v.h[]

=== vfcvt.x.f.v
Mnemonic::
--
	vfcvt.x.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_x_f_v.h[]

=== vfcvt.rtz.xu.f.v
Mnemonic::
--
	vfcvt.rtz.xu.f.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_rtz_xu_f_v.h[]

=== vfcvt.rtz.x.f.v
Mnemonic::
--
	vfcvt.rtz.x.f.v  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_rtz_x_f_v.h[]

=== vfcvt.f.xu.v
Mnemonic::
--
	vfcvt.f.xu.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert unsigned integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_f_xu_v.h[]

=== vfcvt.f.x.v
Mnemonic::
--
	vfcvt.f.x.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert signed integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_f_x_v.h[]

== Widening Floating-Point/Integer Type-Convert Instructions

=== vfwcvt.xu.f.v
Mnemonic::
--
	vfwcvt.xu.f.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to double-width unsigned integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_xu_f_v.h[]

=== vfwcvt.x.f.v
Mnemonic::
--
	vfwcvt.x.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to double-width signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_x_f_v.h[]

=== vfwcvt.rtz.xu.f.v
Mnemonic::
--
	vfwcvt.rtz.xu.f.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to double-width unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_rtz_xu_f_v.h[]

=== vfwcvt.rtz.x.f.v
Mnemonic::
--
	vfwcvt.rtz.x.f.v  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert float to double-width signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_rtz_x_f_v.h[]

=== vfwcvt.f.xu.v
Mnemonic::
--
	vfwcvt.f.xu.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert unsigned integer to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_xu_v.h[]

=== vfwcvt.f.x.v
Mnemonic::
--
	vfwcvt.f.x.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert signed integer to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_x_v.h[]

=== vfwcvt.f.f.v
Mnemonic::
--
	vfwcvt.f.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert single-width float to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_f_v.h[]

== Narrowing Floating-Point/Integer Type-Convert Instructions



=== vfncvt.xu.f.w
Mnemonic::
--
	vfncvt.xu.f.w     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to unsigned integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_xu_f_w.h[]

=== vfncvt.x.f.w
Mnemonic::
--
	vfncvt.x.f.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_x_f_w.h[]

=== vfncvt.rtz.xu.f.w
Mnemonic::
--
	vfncvt.rtz.xu.f.w vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rtz_xu_f_w.h[]

=== vfncvt.rtz.x.f.w
Mnemonic::
--
	vfncvt.rtz.x.f.w  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rtz_x_f_w.h[]

=== vfncvt.f.xu.w
Mnemonic::
--
	vfncvt.f.xu.w     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width unsigned integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_xu_w.h[]

=== vfncvt.f.x.w
Mnemonic::
--
	vfncvt.f.x.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width signed integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_x_w.h[]

=== vfncvt.f.f.w
Mnemonic::
--
	vfncvt.f.f.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to single-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_f_w.h[]

=== vfncvt.rod.f.f.w
Mnemonic::
--
	vfncvt.rod.f.f.w  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Convert double-width float to single-width float, rounding towards odd.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rod_f_f_w.h[]
