== Vector Bitwise Logical Instructions

=== vand.vv

Mnemonic::
--
    vand.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x09, attr: 'vand'},
]}
....


Description::
Bitwise logical operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vand_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vand_vv_intrinsic.cpp[]
----
====


=== vand.vx

Mnemonic::
--
    vand.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0x4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x09, attr: 'vand'},
]}
....

Description::
Bitwise logical operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vand_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vand_vx_intrinsic.cpp[]
----
====


=== vand.vi

Mnemonic::
--
    vand.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x09, attr: 'vand'},
]}
....

Description::
Bitwise logical operations, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vand_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vand_vi_intrinsic.cpp[]
----
====


=== vor.vv

Mnemonic::
--
    vor.vv vd, vs2, vs1, vm
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0a, attr: 'vor'},
]}
....

Description::
Bitwise logical operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vor_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vor_vv_intrinsic.cpp[]
----
====


=== vor.vx

Mnemonic::
--
    vor.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0a, attr: 'vor'},
]}
....

Description::
Bitwise logical operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vor_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vor_vx_intrinsic.cpp[]
----
====


=== vor.vi

Mnemonic::
--
    vor.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0a, attr: 'vor'},
]}
....


Description::
Bitwise logical operations, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vor_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vor_vi_intrinsic.cpp[]
----
====


=== vxor.vv

Mnemonic::
--
    vxor.vv vd, vs2, vs1, vm
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0b, attr: 'vxor'},
]}
....

Description::
Bitwise logical operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vxor_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vxor_vv_intrinsic.cpp[]
----
====


=== vxor.vx

Mnemonic::
--
    vxor.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0b, attr: 'vxor'},
]}
....

Description::
Bitwise logical operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vxor_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vxor_vx_intrinsic.cpp[]
----
====


=== vxor.vi

Mnemonic::
--
    vxor.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x0b, attr: 'vxor'},
]}
....

Description::
Bitwise logical operations, vector-immediate


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vxor_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vxor_vi_intrinsic.cpp[]
----
====


=== Vector Single-Width Shift Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/Vector.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vsll.vv
Mnemonic::
--
    vsll.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x25, attr: 'vsll'},
]}
....

Description::
Bit shift operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsll_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsll_vv_intrinsic.cpp[]
----
====


=== vsll.vx
Mnemonic::
--
    vsll.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x25, attr: 'vsll'},
]}
....

Description::
Bit shift operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsll_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsll_vx_intrinsic.cpp[]
----
====


=== vsll.vi
Mnemonic::
--
    vsll.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x25, attr: 'vsll'},
]}
....


Description::
Bit shift operations, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsll_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsll_vi_intrinsic.cpp[]
----
====


=== vsrl.vv
Mnemonic::
--
    vsrl.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x28, attr: 'vsrl'},
]}
....

Description::
Bit shift operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsrl_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsrl_vv_intrinsic.cpp[]
----
====


=== vsrl.vx
Mnemonic::
--
    vsrl.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x28, attr: 'vsrl'},
]}
....

Description::
Bit shift operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsrl_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsrl_vx_intrinsic.cpp[]
----
====


=== vsrl.vi
Mnemonic::
--
    vsrl.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x28, attr: 'vsrl'},
]}
....

Description::
Bit shift operations, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsrl_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsrl_vi_intrinsic.cpp[]
----
====


=== vsra.vv
Mnemonic::
--
    vsra.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x29, attr: 'vsra'},
]}
....

Description::
Bit shift operations, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsra_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsra_vv_intrinsic.cpp[]
----
====


=== vsra.vx
Mnemonic::
--
    vsra.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x29, attr: 'vsra'},
]}
....


Description::
Bit shift operations, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsra_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsra_vx_intrinsic.cpp[]
----
====


=== vsra.vi
Mnemonic::
--
    vsra.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x29, attr: 'vsra'},
]}
....

Description::
Bit shift operations, vector-immediate


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsra_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsra_vi_intrinsic.cpp[]
----
====


=== Vector Narrowing Integer Right Shift Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/Vector.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vnsrl.wv

Mnemonic::
--
    vnsrl.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2c, attr: 'vnsrl'},
]}
....

Description::
Narrowing shift right logical, SEW = (2*SEW) >> SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsrl_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsrl_wv_intrinsic.cpp[]
----
====


=== vnsrl.wx

Mnemonic::
--
    vnsrl.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2c, attr: 'vnsrl'},
]}
....

Description::
Narrowing shift right logical, SEW = (2*SEW) >> SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsrl_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsrl_wx_intrinsic.cpp[]
----
====


=== vnsrl.wi

Mnemonic::
--
    vnsrl.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2c, attr: 'vnsrl'},
]}
....

Description::
Narrowing shift right logical, SEW = (2*SEW) >> SEW, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsrl_wi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsrl_wi_intrinsic.cpp[]
----
====


=== vnsra.wv

Mnemonic::
--
    vnsra.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2d, attr: 'vnsra'},
]}
....


Description::
Narrowing shift right arithmetic, SEW = (2*SEW) >> SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsra_wv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsra_wv_intrinsic.cpp[]
----
====


=== vnsra.wx

Mnemonic::
--
    vnsra.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2d, attr: 'vnsra'},
]}
....

Description::
Narrowing shift right arithmetic, SEW = (2*SEW) >> SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsra_wx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsra_wx_intrinsic.cpp[]
----
====


=== vnsra.wi

Mnemonic::
--
    vnsra.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x2d, attr: 'vnsra'},
]}
....

Description::
Narrowing shift right arithmetic, SEW = (2*SEW) >> SEW, vector-immediate



Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnsra_wi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnsra_wi_intrinsic.cpp[]
----
====


=== Vector Integer Compare Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/Vector.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vmseq.vv

Mnemonic::
--
    vmseq.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x18, attr: 'vmseq'},
]}
....

Description::
Set if equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmseq_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmseq_vv_intrinsic.cpp[]
----
====


=== vmseq.vx

Mnemonic::
--
    vmseq.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x18, attr: 'vmseq'},
]}
....

Description::
Set if equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmseq_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmseq_vx_intrinsic.cpp[]
----
====


=== vmseq.vi

Mnemonic::
--
    vmseq.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x18, attr: 'vmseq'},
]}
....

Description::
Set if equal, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmseq_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmseq_vi_intrinsic.cpp[]
----
====


=== vmsne.vv

Mnemonic::
--
    vmsne.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x19, attr: 'vmsne'},
]}
....

Description::
Set if not equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsne_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsne_vv_intrinsic.cpp[]
----
====


=== vmsne.vx

Mnemonic::
--
    vmsne.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x19, attr: 'vmsne'},
]}
....


Description::
Set if not equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsne_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsne_vx_intrinsic.cpp[]
----
====


=== vmsne.vi

Mnemonic::
--
    vmsne.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x19, attr: 'vmsne'},
]}
....

Description::
Set if not equal, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsne_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsne_vi_intrinsic.cpp[]
----
====


=== vmsltu.vv

Mnemonic::
--
    vmsltu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1a, attr: 'vmsltu'},
]}
....

Description::
Set if less than, unsigned, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsltu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsltu_vv_intrinsic.cpp[]
----
====


=== vmsltu.vx

Mnemonic::
--
    vmsltu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1a, attr: 'vmsltu'},
]}
....

Description::
Set if less than, unsigned, Vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsltu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsltu_vx_intrinsic.cpp[]
----
====


=== vmslt.vv

Mnemonic::
--
    vmslt.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1b, attr: 'vmslt'},
]}
....

Description::
Set if less than, signed, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmslt_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmslt_vv_intrinsic.cpp[]
----
====


=== vmslt.vx

Mnemonic::
--
    vmslt.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1b, attr: 'vmslt'},
]}
....

Description::
Set if less than, signed, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmslt_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmslt_vx_intrinsic.cpp[]
----
====


=== vmsleu.vv

Mnemonic::
--
    vmsleu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1c, attr: 'vmsleu'},
]}
....

Description::
Set if less than or equal, unsigned, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsleu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsleu_vv_intrinsic.cpp[]
----
====


=== vmsleu.vx

Mnemonic::
--
    vmsleu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1c, attr: 'vmsleu'},
]}
....

Description::
Set if less than or equal, unsigned, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsleu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsleu_vx_intrinsic.cpp[]
----
====


=== vmsleu.vi

Mnemonic::
--
    vmsleu.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1c, attr: 'vmsleu'},
]}
....

Description::
Set if less than or equal, unsigned, Vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsleu_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsleu_vi_intrinsic.cpp[]
----
====


=== vmsle.vv

Mnemonic::
--
    vmsle.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1d, attr: 'vmsle'},
]}
....

Description::
Set if less than or equal, signed, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsle_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsle_vv_intrinsic.cpp[]
----
====


=== vmsle.vx

Mnemonic::
--
    vmsle.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1d, attr: 'vmsle'},
]}
....

Description::
Set if less than or equal, signed, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsle_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsle_vx_intrinsic.cpp[]
----
====


=== vmsle.vi

Mnemonic::
--
    vmsle.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1d, attr: 'vmsle'},
]}
....

Description::
Set if less than or equal, signed, vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsle_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsle_vi_intrinsic.cpp[]
----
====


=== vmsgtu.vx

Mnemonic::
--
    vmsgtu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1e, attr: 'vmsgtu'},
]}
....

Description::
Set if greater than, unsigned, Vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsgtu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsgtu_vx_intrinsic.cpp[]
----
====


=== vmsgtu.vi

Mnemonic::
--
    vmsgtu.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1e, attr: 'vmsgtu'},
]}
....

Description::
Set if greater than, unsigned, Vector-immediate

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsgtu_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsgtu_vi_intrinsic.cpp[]
----
====


=== vmsgt.vx

Mnemonic::
--
    vmsgt.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1f, attr: 'vmsgt'},
]}
....

Description::
Set if greater than, signed, Vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsgt_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsgt_vx_intrinsic.cpp[]
----
====


=== vmsgt.vi

Mnemonic::
--
    vmsgt.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x1f, attr: 'vmsgt'},
]}
....

Description::
Set if greater than, signed, Vector-immediate



Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsgt_vi.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsgt_vi_intrinsic.cpp[]
----
====


=== Vector Integer Min/Max Instructions

Signed and unsigned integer minimum and maximum instructions are
supported.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/Vector.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vminu.vv

Mnemonic::
--
    vminu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x04, attr: 'vminu'},
]}
....

Description::
 Unsigned minimum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vminu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vminu_vv_intrinsic.cpp[]
----
====


=== vminu.vx

Mnemonic::
--
    vminu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x04, attr: 'vminu'},
]}
....

Description::
 Unsigned minimum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vminu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vminu_vx_intrinsic.cpp[]
----
====


=== vmin.vv

Mnemonic::
--
    vmin.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x05, attr: 'vmin'},
]}
....

Description::
Signed minimum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmin_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmin_vv_intrinsic.cpp[]
----
====


=== vmin.vx

Mnemonic::
--
    vmin.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x05, attr: 'vmin'},
]}
....

Description::
Signed minimum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmin_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmin_vx_intrinsic.cpp[]
----
====


=== vmaxu.vv

Mnemonic::
--
    vmaxu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x06, attr: 'vmaxu'},
]}
....

Description::
 Unsigned maximum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmaxu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmaxu_vv_intrinsic.cpp[]
----
====


=== vmaxu.vx

Mnemonic::
--
    vmaxu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x06, attr: 'vmaxu'},
]}
....

Description::
 Unsigned maximum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmaxu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmaxu_vx_intrinsic.cpp[]
----
====


=== vmax.vv

Mnemonic::
--
    vmax.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x07, attr: 'vmax'},
]}
....

Description::
Signed maximum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmax_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmax_vv_intrinsic.cpp[]
----
====


=== vmax.vx

Mnemonic::
--
    vmax.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0x1, attr: 'vm'},
  {bits: 6, name: 0x07, attr: 'vmax'},
]}
....

Description::
Signed maximum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmax_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmax_vx_intrinsic.cpp[]
----
====


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmax_v_intrinsic.cpp[]
----
====
