== Vector Unit-Stride Instructions

=== vle8.v

Mnemonic::
--
    vle8.v    vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
8-bit unit-stride load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle8_v.h[]

=== vle16.v

Mnemonic::
--
    vle16.v   vd, (rs1), vm
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
16-bit unit-stride load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle16_v.h[]

=== vle32.v

Mnemonic::
--
    vle32.v   vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
32-bit unit-stride load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle32_v.h[]

=== vle64.v

Mnemonic::
--
    vle64.v   vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
64-bit unit-stride load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle64_v.h[]

=== vse8.v

https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/main/auto-generated/intrinsic_funcs/01_vector_loads_and_stores_functions.md#vector-unit-stride-store-functions

Mnemonic::
--
    vse8.v    vs3, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
8-bit unit-stride store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse8_v.h[]

=== vse16.v

Mnemonic::
--
    vse16.v   vs3, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
16-bit unit-stride store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse16_v.h[]

=== vse32.v

Mnemonic::
--
    vse32.v   vs3, (rs1), vm
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
32-bit unit-stride store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse32_v.h[]

=== vse64.v

Mnemonic::
--
    vse64.v   vs3, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
64-bit unit-stride store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse64_v.h[]

=== vlm.v

Mnemonic::
--
    vlm.v vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0xb, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
Vector unit-stride mask load
Load byte vector of length ceil(vl/8)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlm_v.h[]


=== vsm.v

Mnemonic::
--
    vsm.v vs3, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0xb, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
Vector unit-stride mask store
Store byte vector of length ceil(vl/8)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsm_v.h[]

== Vector Strided Instructions

=== vlse8.v
Mnemonic::
--
    vlse8.v    vd, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
8-bit strided load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse8_v.h[]

=== vlse16.v

Mnemonic::
--
    vlse16.v   vd, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
16-bit strided load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse16_v.h[]

=== vlse32.v
Mnemonic::
--
    vlse32.v   vd, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
32-bit strided load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse32_v.h[]

=== vlse64.v
Mnemonic::
--
    vlse64.v   vd, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
64-bit strided load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse64_v.h[]

=== vsse8.v
Mnemonic::
--
    vsse8.v    vs3, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
8-bit strided store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse8_v.h[]

=== vsse16.v
Mnemonic::
--
    vsse16.v   vs3, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
16-bit strided store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse16_v.h[]

=== vsse32.v
Mnemonic::
--
    vsse32.v   vs3, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
32-bit strided store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse32_v.h[]

=== vsse64.v
Mnemonic::
--
    vsse64.v   vs3, (rs1), rs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
64-bit strided store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse64_v.h[]

== Vector Indexed Instructions

=== vluxei8.v

Mnemonic::
--
    vluxei8.v    vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered  8-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei8_v.h[]

=== vluxei16.v

Mnemonic::
--
	vluxei16.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 16-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei16_v.h[]

=== vluxei32.v
Mnemonic::
--
	vluxei32.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 32-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei32_v.h[]

=== vluxei64.v
Mnemonic::
--
	vluxei64.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 64-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei64_v.h[]

=== vloxei8.v
Mnemonic::
--
	vloxei8.v    vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered  8-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei8_v.h[]


=== vloxei16.v
Mnemonic::
--
	vloxei16.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 16-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei16_v.h[]

=== vloxei32.v
Mnemonic::
--
	vloxei32.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 32-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei32_v.h[]

=== vloxei64.v
Mnemonic::
--
	vloxei64.v   vd, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 64-bit indexed load of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei64_v.h[]

=== vsuxei8.v
Mnemonic::
--
	vsuxei8.v   vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
unordered  8-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei8_v.h[]

=== vsuxei16.v
Mnemonic::
--
	vsuxei16.v  vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 16-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei16_v.h[]

=== vsuxei32.v
Mnemonic::
--
	vsuxei32.v  vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 32-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei32_v.h[]

=== vsuxei64.v
Mnemonic::
--
	vsuxei64.v  vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
unordered 64-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei64_v.h[]

=== vsoxei8.v
Mnemonic::
--
	vsoxei8.v    vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered  8-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei8_v.h[]

=== vsoxei16.v
Mnemonic::
--
	vsoxei16.v   vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 16-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei16_v.h[]

=== vsoxei32.v

Mnemonic::
--
	vsoxei32.v   vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 32-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei16_v.h[]

=== vsoxei64.v

Mnemonic::
--
	vsoxei64.v   vs3, (rs1), vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
ordered 64-bit indexed store of SEW data

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei64_v.h[]

== Unit-stride Fault-Only-First Loads

=== vle8ff.v

Mnemonic::
--
	vle8ff.v    vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x10, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
8-bit unit-stride fault-only-first load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle8ff_v.h[]

=== vle16ff.v

Mnemonic::
--
	vle16ff.v   vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x10, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
16-bit unit-stride fault-only-first load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle16ff_v.h[]

=== vle32ff.v

Mnemonic::
--
	vle32ff.v   vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x10, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
32-bit unit-stride fault-only-first load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle32ff_v.h[]

=== vle64ff.v

Mnemonic::
--
	vle64ff.v   vd, (rs1), vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x10, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
64-bit unit-stride fault-only-first load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle64ff_v.h[]

== Vector Unit-Stride Segment Loads and Stores

=== vlseg<nf>e8.v

Mnemonic::
--
    vlseg2e8.v vd, (rs1), vm	# nf=2
    vlseg3e8.v vd, (rs1), vm	# nf=3
    vlseg4e8.v vd, (rs1), vm	# nf=4
    vlseg5e8.v vd, (rs1), vm	# nf=5
    vlseg6e8.v vd, (rs1), vm	# nf=6
    vlseg7e8.v vd, (rs1), vm	# nf=7
    vlseg8e8.v vd, (rs1), vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
8-bit Unit-stride segment load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle8_v.h[]

=== vlseg<nf>e16.v

Mnemonic::
--
    vlseg2e16.v vd, (rs1), vm    # nf=2
    vlseg3e16.v vd, (rs1), vm    # nf=3
    vlseg4e16.v vd, (rs1), vm    # nf=4
    vlseg5e16.v vd, (rs1), vm    # nf=5
    vlseg6e16.v vd, (rs1), vm    # nf=6
    vlseg7e16.v vd, (rs1), vm    # nf=7
    vlseg8e16.v vd, (rs1), vm    # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
16-bit Unit-stride segment load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle16_v.h[]

=== vlseg<nf>e32.v

Mnemonic::
--
    vlseg2e32.v vd, (rs1), vm    # nf=2
    vlseg3e32.v vd, (rs1), vm    # nf=3
    vlseg4e32.v vd, (rs1), vm    # nf=4
    vlseg5e32.v vd, (rs1), vm    # nf=5
    vlseg6e32.v vd, (rs1), vm    # nf=6
    vlseg7e32.v vd, (rs1), vm    # nf=7
    vlseg8e32.v vd, (rs1), vm    # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
32-bit Unit-stride segment load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle32_v.h[]

=== vlseg<nf>e64.v

Mnemonic::
--
    vlseg2e64.v vd, (rs1), vm    # nf=2
    vlseg3e64.v vd, (rs1), vm    # nf=3
    vlseg4e64.v vd, (rs1), vm    # nf=4
    vlseg5e64.v vd, (rs1), vm    # nf=5
    vlseg6e64.v vd, (rs1), vm    # nf=6
    vlseg7e64.v vd, (rs1), vm    # nf=7
    vlseg8e64.v vd, (rs1), vm    # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VL* unit-stride'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'lumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
64-bit Unit-stride segment load

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vle64_v.h[]

=== vsseg<nf>e8.v

Mnemonic::
--
	vsseg2e8.v vs3, (rs1), vm	# nf=2
	vsseg3e8.v vs3, (rs1), vm	# nf=3
	vsseg4e8.v vs3, (rs1), vm	# nf=4
	vsseg5e8.v vs3, (rs1), vm	# nf=5
	vsseg6e8.v vs3, (rs1), vm	# nf=6
	vsseg7e8.v vs3, (rs1), vm	# nf=7
	vsseg8e8.v vs3, (rs1), vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
8-bit Unit-stride segment store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse8_v.h[]

=== vsseg<nf>e16.v

Mnemonic::
--
	vsseg2e16.v vs3, (rs1), vm	# nf=2
	vsseg3e16.v vs3, (rs1), vm	# nf=3
	vsseg4e16.v vs3, (rs1), vm	# nf=4
	vsseg5e16.v vs3, (rs1), vm	# nf=5
	vsseg6e16.v vs3, (rs1), vm	# nf=6
	vsseg7e16.v vs3, (rs1), vm	# nf=7
	vsseg8e16.v vs3, (rs1), vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
16-bit Unit-stride segment store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse16_v.h[]

=== vsseg<nf>e32.v

Mnemonic::
--
	vsseg2e32.v vs3, (rs1), vm	# nf=2
	vsseg3e32.v vs3, (rs1), vm	# nf=3
	vsseg4e32.v vs3, (rs1), vm	# nf=4
	vsseg5e32.v vs3, (rs1), vm	# nf=5
	vsseg6e32.v vs3, (rs1), vm	# nf=6
	vsseg7e32.v vs3, (rs1), vm	# nf=7
	vsseg8e32.v vs3, (rs1), vm	# nf=8
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
32-bit Unit-stride segment store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse32_v.h[]


=== vsseg<nf>e64.v

Mnemonic::
--
	vsseg2e64.v vs3, (rs1), vm	# nf=2
	vsseg3e64.v vs3, (rs1), vm	# nf=3
	vsseg4e64.v vs3, (rs1), vm	# nf=4
	vsseg5e64.v vs3, (rs1), vm	# nf=5
	vsseg6e64.v vs3, (rs1), vm	# nf=6
	vsseg7e64.v vs3, (rs1), vm	# nf=7
	vsseg8e64.v vs3, (rs1), vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS* unit-stride'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 0x0, attr: 'sumop'},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x0, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
64-bit Unit-stride segment store

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vse64_v.h[]

== Vector Strided Segment Loads and Stores

=== vlsseg<nf>e8.v

Mnemonic::
--
	vlsseg2e8.v vd, (rs1), rs2, vm  # nf=2
	vlsseg3e8.v vd, (rs1), rs2, vm  # nf=3
	vlsseg4e8.v vd, (rs1), rs2, vm  # nf=4
	vlsseg5e8.v vd, (rs1), rs2, vm  # nf=5
	vlsseg6e8.v vd, (rs1), rs2, vm  # nf=6
	vlsseg7e8.v vd, (rs1), rs2, vm  # nf=7
	vlsseg8e8.v vd, (rs1), rs2, vm  # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse8_v.h[]

=== vlsseg<nf>e16.v

Mnemonic::
--
	vlsseg2e16.v vd, (rs1), rs2, vm  # nf=2
	vlsseg3e16.v vd, (rs1), rs2, vm  # nf=3
	vlsseg4e16.v vd, (rs1), rs2, vm  # nf=4
	vlsseg5e16.v vd, (rs1), rs2, vm  # nf=5
	vlsseg6e16.v vd, (rs1), rs2, vm  # nf=6
	vlsseg7e16.v vd, (rs1), rs2, vm  # nf=7
	vlsseg8e16.v vd, (rs1), rs2, vm  # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
16-bit Strided segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse16_v.h[]

=== vlsseg<nf>e32.v

Mnemonic::
--
	vlsseg2e32.v vd, (rs1), rs2, vm  # nf=2
	vlsseg3e32.v vd, (rs1), rs2, vm  # nf=3
	vlsseg4e32.v vd, (rs1), rs2, vm  # nf=4
	vlsseg5e32.v vd, (rs1), rs2, vm  # nf=5
	vlsseg6e32.v vd, (rs1), rs2, vm  # nf=6
	vlsseg7e32.v vd, (rs1), rs2, vm  # nf=7
	vlsseg8e32.v vd, (rs1), rs2, vm  # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
32-bit Strided segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse32_v.h[]

=== vlsseg<nf>e64.v

Mnemonic::
--
	vlsseg2e64.v vd, (rs1), rs2, vm  # nf=2
	vlsseg3e64.v vd, (rs1), rs2, vm  # nf=3
	vlsseg4e64.v vd, (rs1), rs2, vm  # nf=4
	vlsseg5e64.v vd, (rs1), rs2, vm  # nf=5
	vlsseg6e64.v vd, (rs1), rs2, vm  # nf=6
	vlsseg7e64.v vd, (rs1), rs2, vm  # nf=7
	vlsseg8e64.v vd, (rs1), rs2, vm  # nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLS* strided'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
64-bit Strided segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vlse64_v.h[]

=== vssseg2e8.v

Mnemonic::
--
	vssseg2e8.v vs3, (rs1), rs2, vm	# nf=2
	vssseg3e8.v vs3, (rs1), rs2, vm	# nf=3
	vssseg4e8.v vs3, (rs1), rs2, vm	# nf=4
	vssseg5e8.v vs3, (rs1), rs2, vm	# nf=5
	vssseg6e8.v vs3, (rs1), rs2, vm	# nf=6
	vssseg7e8.v vs3, (rs1), rs2, vm	# nf=7
	vssseg8e8.v vs3, (rs1), rs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
8-bit strided segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse8_v.h[]

=== vssseg2e16.v

Mnemonic::
--
	vssseg2e16.v vs3, (rs1), rs2, vm	# nf=2
	vssseg3e16.v vs3, (rs1), rs2, vm	# nf=3
	vssseg4e16.v vs3, (rs1), rs2, vm	# nf=4
	vssseg5e16.v vs3, (rs1), rs2, vm	# nf=5
	vssseg6e16.v vs3, (rs1), rs2, vm	# nf=6
	vssseg7e16.v vs3, (rs1), rs2, vm	# nf=7
	vssseg8e16.v vs3, (rs1), rs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
16-bit strided segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse16_v.h[]

=== vssseg2e32.v

Mnemonic::
--
	vssseg2e32.v vs3, (rs1), rs2, vm	# nf=2
	vssseg3e32.v vs3, (rs1), rs2, vm	# nf=3
	vssseg4e32.v vs3, (rs1), rs2, vm	# nf=4
	vssseg5e32.v vs3, (rs1), rs2, vm	# nf=5
	vssseg6e32.v vs3, (rs1), rs2, vm	# nf=6
	vssseg7e32.v vs3, (rs1), rs2, vm	# nf=7
	vssseg8e32.v vs3, (rs1), rs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
32-bit strided segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse32_v.h[]

=== vssseg2e64.v

Mnemonic::
--
	vssseg2e64.v vs3, (rs1), rs2, vm	# nf=2
	vssseg3e64.v vs3, (rs1), rs2, vm	# nf=3
	vssseg4e64.v vs3, (rs1), rs2, vm	# nf=4
	vssseg5e64.v vs3, (rs1), rs2, vm	# nf=5
	vssseg6e64.v vs3, (rs1), rs2, vm	# nf=6
	vssseg7e64.v vs3, (rs1), rs2, vm	# nf=7
	vssseg8e64.v vs3, (rs1), rs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSS* strided'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'rs2', attr: 'stride', type: 4},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
64-bit strided segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsse64_v.h[]

== Vector Indexed Segment Loads and Stores

Mnemonic::
--
	vluxseg2ei8.v vd, (rs1), vs2, vm	# nf=2
	vluxseg3ei8.v vd, (rs1), vs2, vm	# nf=3
	vluxseg4ei8.v vd, (rs1), vs2, vm	# nf=4
	vluxseg5ei8.v vd, (rs1), vs2, vm	# nf=5
	vluxseg6ei8.v vd, (rs1), vs2, vm	# nf=6
	vluxseg7ei8.v vd, (rs1), vs2, vm	# nf=7
	vluxseg8ei8.v vd, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei8_v.h[]

Mnemonic::
--
	vluxseg2ei16.v vd, (rs1), vs2, vm	# nf=2
	vluxseg3ei16.v vd, (rs1), vs2, vm	# nf=3
	vluxseg4ei16.v vd, (rs1), vs2, vm	# nf=4
	vluxseg5ei16.v vd, (rs1), vs2, vm	# nf=5
	vluxseg6ei16.v vd, (rs1), vs2, vm	# nf=6
	vluxseg7ei16.v vd, (rs1), vs2, vm	# nf=7
	vluxseg8ei16.v vd, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei16_v.h[]

Mnemonic::
--
	vluxseg2ei32.v vd, (rs1), vs2, vm	# nf=2
	vluxseg3ei32.v vd, (rs1), vs2, vm	# nf=3
	vluxseg4ei32.v vd, (rs1), vs2, vm	# nf=4
	vluxseg5ei32.v vd, (rs1), vs2, vm	# nf=5
	vluxseg6ei32.v vd, (rs1), vs2, vm	# nf=6
	vluxseg7ei32.v vd, (rs1), vs2, vm	# nf=7
	vluxseg8ei32.v vd, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....


Description::
Indexed-unordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei32_v.h[]

Mnemonic::
--
	vluxseg2ei64.v vd, (rs1), vs2, vm	# nf=2
	vluxseg3ei64.v vd, (rs1), vs2, vm	# nf=3
	vluxseg4ei64.v vd, (rs1), vs2, vm	# nf=4
	vluxseg5ei64.v vd, (rs1), vs2, vm	# nf=5
	vluxseg6ei64.v vd, (rs1), vs2, vm	# nf=6
	vluxseg7ei64.v vd, (rs1), vs2, vm	# nf=7
	vluxseg8ei64.v vd, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x1, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vluxei64_v.h[]

=== vloxseg<nf>ei8.v

Mnemonic::
--
	vloxseg2ei8.v vd, (rs1), vs2, vm	# nf=2
	vloxseg3ei8.v vd, (rs1), vs2, vm	# nf=3
	vloxseg4ei8.v vd, (rs1), vs2, vm	# nf=4
	vloxseg5ei8.v vd, (rs1), vs2, vm	# nf=5
	vloxseg6ei8.v vd, (rs1), vs2, vm	# nf=6
	vloxseg7ei8.v vd, (rs1), vs2, vm	# nf=7
	vloxseg8ei8.v vd, (rs1), vs2, vm	# nf=8
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr:'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-ordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei8_v.h[]

=== vloxseg<nf>ei16.v

Mnemonic::
--
	vloxseg2ei16.v vd, (rs1), vs2, vm	# nf=2
	vloxseg3ei16.v vd, (rs1), vs2, vm	# nf=3
	vloxseg4ei16.v vd, (rs1), vs2, vm	# nf=4
	vloxseg5ei16.v vd, (rs1), vs2, vm	# nf=5
	vloxseg6ei16.v vd, (rs1), vs2, vm	# nf=6
	vloxseg7ei16.v vd, (rs1), vs2, vm	# nf=7
	vloxseg8ei16.v vd, (rs1), vs2, vm	# nf=8
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr:'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-ordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei16_v.h[]

=== vloxseg<nf>ei32.v

Mnemonic::
--
	vloxseg2ei32.v vd, (rs1), vs2, vm	# nf=2
	vloxseg3ei32.v vd, (rs1), vs2, vm	# nf=3
	vloxseg4ei32.v vd, (rs1), vs2, vm	# nf=4
	vloxseg5ei32.v vd, (rs1), vs2, vm	# nf=5
	vloxseg6ei32.v vd, (rs1), vs2, vm	# nf=6
	vloxseg7ei32.v vd, (rs1), vs2, vm	# nf=7
	vloxseg8ei32.v vd, (rs1), vs2, vm	# nf=8
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr:'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-ordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei32_v.h[]

=== vloxseg<nf>ei64.v

Mnemonic::
--
	vloxseg2ei64.v vd, (rs1), vs2, vm	# nf=2
	vloxseg3ei64.v vd, (rs1), vs2, vm	# nf=3
	vloxseg4ei64.v vd, (rs1), vs2, vm	# nf=4
	vloxseg5ei64.v vd, (rs1), vs2, vm	# nf=5
	vloxseg6ei64.v vd, (rs1), vs2, vm	# nf=6
	vloxseg7ei64.v vd, (rs1), vs2, vm	# nf=7
	vloxseg8ei64.v vd, (rs1), vs2, vm	# nf=8
--


Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x7, attr: 'VLX* indexed'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr:'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-ordered segment loads

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vloxei64_v.h[]

=== vsuxseg<nf>ei8.v

Mnemonic::
--
	vsuxseg2ei8.v vs3, (rs1), vs2, vm	# nf=2
	vsuxseg3ei8.v vs3, (rs1), vs2, vm	# nf=3
	vsuxseg4ei8.v vs3, (rs1), vs2, vm	# nf=4
	vsuxseg5ei8.v vs3, (rs1), vs2, vm	# nf=5
	vsuxseg6ei8.v vs3, (rs1), vs2, vm	# nf=6
	vsuxseg7ei8.v vs3, (rs1), vs2, vm	# nf=7
	vsuxseg8ei8.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei8_v.h[]

=== vsuxseg<nf>ei16.v

Mnemonic::
--
	vsuxseg2ei16.v vs3, (rs1), vs2, vm	# nf=2
	vsuxseg3ei16.v vs3, (rs1), vs2, vm	# nf=3
	vsuxseg4ei16.v vs3, (rs1), vs2, vm	# nf=4
	vsuxseg5ei16.v vs3, (rs1), vs2, vm	# nf=5
	vsuxseg6ei16.v vs3, (rs1), vs2, vm	# nf=6
	vsuxseg7ei16.v vs3, (rs1), vs2, vm	# nf=7
	vsuxseg8ei16.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei16_v.h[]

=== vsuxseg<nf>ei32.v

Mnemonic::
--
	vsuxseg2ei32.v vs3, (rs1), vs2, vm	# nf=2
	vsuxseg3ei32.v vs3, (rs1), vs2, vm	# nf=3
	vsuxseg4ei32.v vs3, (rs1), vs2, vm	# nf=4
	vsuxseg5ei32.v vs3, (rs1), vs2, vm	# nf=5
	vsuxseg6ei32.v vs3, (rs1), vs2, vm	# nf=6
	vsuxseg7ei32.v vs3, (rs1), vs2, vm	# nf=7
	vsuxseg8ei32.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei32_v.h[]

=== vsuxseg<nf>ei64.v

Mnemonic::
--
	vsuxseg2ei64.v vs3, (rs1), vs2, vm	# nf=2
	vsuxseg3ei64.v vs3, (rs1), vs2, vm	# nf=3
	vsuxseg4ei64.v vs3, (rs1), vs2, vm	# nf=4
	vsuxseg5ei64.v vs3, (rs1), vs2, vm	# nf=5
	vsuxseg6ei64.v vs3, (rs1), vs2, vm	# nf=6
	vsuxseg7ei64.v vs3, (rs1), vs2, vm	# nf=7
	vsuxseg8ei64.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x2, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsuxei64_v.h[]

=== vsoxseg<nf>ei8.v

Mnemonic::
--
	vsoxseg2ei8.v vs3, (rs1), vs2, vm	# nf=2
	vsoxseg3ei8.v vs3, (rs1), vs2, vm	# nf=3
	vsoxseg4ei8.v vs3, (rs1), vs2, vm	# nf=4
	vsoxseg5ei8.v vs3, (rs1), vs2, vm	# nf=5
	vsoxseg6ei8.v vs3, (rs1), vs2, vm	# nf=6
	vsoxseg7ei8.v vs3, (rs1), vs2, vm	# nf=7
	vsoxseg8ei8.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei8_v.h[]

=== vsoxseg<nf>ei16.v

Mnemonic::
--
	vsoxseg2ei16.v vs3, (rs1), vs2, vm	# nf=2
	vsoxseg3ei16.v vs3, (rs1), vs2, vm	# nf=3
	vsoxseg4ei16.v vs3, (rs1), vs2, vm	# nf=4
	vsoxseg5ei16.v vs3, (rs1), vs2, vm	# nf=5
	vsoxseg6ei16.v vs3, (rs1), vs2, vm	# nf=6
	vsoxseg7ei16.v vs3, (rs1), vs2, vm	# nf=7
	vsoxseg8ei16.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei16_v.h[]

=== vsoxseg<nf>ei32.v

Mnemonic::
--
	vsoxseg2ei32.v vs3, (rs1), vs2, vm	# nf=2
	vsoxseg3ei32.v vs3, (rs1), vs2, vm	# nf=3
	vsoxseg4ei32.v vs3, (rs1), vs2, vm	# nf=4
	vsoxseg5ei32.v vs3, (rs1), vs2, vm	# nf=5
	vsoxseg6ei32.v vs3, (rs1), vs2, vm	# nf=6
	vsoxseg7ei32.v vs3, (rs1), vs2, vm	# nf=7
	vsoxseg8ei32.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei32_v.h[]

=== vsoxseg<nf>ei64.v

Mnemonic::
--
	vsoxseg2ei64.v vs3, (rs1), vs2, vm	# nf=2
	vsoxseg3ei64.v vs3, (rs1), vs2, vm	# nf=3
	vsoxseg4ei64.v vs3, (rs1), vs2, vm	# nf=4
	vsoxseg5ei64.v vs3, (rs1), vs2, vm	# nf=5
	vsoxseg6ei64.v vs3, (rs1), vs2, vm	# nf=6
	vsoxseg7ei64.v vs3, (rs1), vs2, vm	# nf=7
	vsoxseg8ei64.v vs3, (rs1), vs2, vm	# nf=8
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VSX* indexed'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 'vs2', attr: 'address offsets', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 2, name: 0x3, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 'nf-1'},
]}
....

Description::
Indexed-unordered segment stores

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vsoxei64_v.h[]

== Vector Load/Store Whole Register Instructions

=== vl1re8.v

Mnemonic::
--
	vl1re8.v    vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
Load `vd` with VLEN/8 bytes held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl1re8_v.h[]

=== vl1re16.v

Mnemonic::
--
	vl1re16.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
Load `vd` with VLEN/16 halfwords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl1re16_v.h[]

=== vl1re32.v

Mnemonic::
--
	vl1re32.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
Load `vd` with VLEN/32 words held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl1re32_v.h[]

=== vl1re64.v

Mnemonic::
--
	vl1re64.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....


Description::
Load `vd` with VLEN/64 doublewords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl1re64_v.h[]

=== vl2re8.v

Mnemonic::
--
	vl2re8.v    vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x1, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+1` with VLEN/8 bytes held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl2re8_v.h[]

=== vl2re16.v

Mnemonic::
--
	vl2re16.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x1, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+1` with VLEN/16 halfwords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl2re16_v.h[]

=== vl2re32.v

Mnemonic::
--
	vl2re32.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x1, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+1` with VLEN/32 words held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl2re32_v.h[]

=== vl2re64.v

Mnemonic::
--
	vl2re64.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x1, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+1` with VLEN/64 doublewords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl2re64_v.h[]


=== vl4re8.v

Mnemonic::
--
	vl4re8.v    vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x3, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+3` with VLEN/8 bytes held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl4re8_v.h[]

=== vl4re16.v

Mnemonic::
--
	vl4re16.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x3, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+3` with VLEN/16 halfwords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl4re16_v.h[]

=== vl4re32.v

Mnemonic::
--
	vl4re32.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x3, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+3` with VLEN/32 words held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl4re32_v.h[]

=== vl4re64.v

Mnemonic::
--
	vl4re64.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x3, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+3` with VLEN/64 doublewords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl4re64_v.h[]

=== vl8re8.v

Mnemonic::
--
	vl8re8.v    vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x0, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x7, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+7` with VLEN/8 bytes held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl8re8_v.h[]

=== vl8re16.v

Mnemonic::
--
	vl8re16.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x5, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x7, attr: 'nf'},
]}
....

Description::
Load `vd`-`vd+7` with VLEN/16 halfwords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl8re16_v.h[]

=== vl8re32.v

Mnemonic::
--
	vl8re32.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x6, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x7, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+7` with VLEN/32 words held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl8re32_v.h[]

=== vl8re64.v

Mnemonic::
--
	vl8re64.v   vd, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x07, attr: 'VL*R*'},
  {bits: 5, name: 'vd', attr: 'destination of load', type: 2},
  {bits: 3, name: 0x7, attr: 'width'},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'lumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x10000, attr: 'mop'},
  {bits: 1, name: 0x0, attr: 'mew'},
  {bits: 3, name: 0x7, attr: 'nf'},
]}
....


Description::
Load `vd`-`vd+7` with VLEN/64 doublewords held at address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vl8re64_v.h[]

=== vs1r.v

Mnemonic::
--
    vs1r.v vs3, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS*R*'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x1000},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'sumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x100, attr: 'mop'},
  {bits: 1, name: 0x100, attr: 'mew'},
  {bits: 3, name: 0x0, attr: 'nf'},
]}
....

Description::
Store `vs3` to address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vs1r_v.h[]

=== vs2r.v

Mnemonic::
--
    vs2r.v vs3, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS*R*'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x1000},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'sumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x100, attr: 'mop'},
  {bits: 1, name: 0x100, attr: 'mew'},
  {bits: 3, name: 0x1, attr: 'nf'},
]}
....

Description::
Store `vs3`-`vs3+1` to address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vs2r_v.h[]

=== vs4r.v

Mnemonic::
--
    vs4r.v vs3, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS*R*'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x1000},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'sumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x100, attr: 'mop'},
  {bits: 1, name: 0x100, attr: 'mew'},
  {bits: 3, name: 0x3, attr: 'nf'},
]}
....

Description::
Store `vs3`-`vs3+3` to address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vs4r_v.h[]

=== vs8r.v

Mnemonic::
--
    vs8r.v vs3, (rs1)
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x27, attr: 'VS*R*'},
  {bits: 5, name: 'vs3', attr: 'store data', type: 2},
  {bits: 3, name: 0x1000},
  {bits: 5, name: 'rs1', attr: 'base address', type: 4},
  {bits: 5, name: 8, attr: 'sumop'},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 2, name: 0x100, attr: 'mop'},
  {bits: 1, name: 0x100, attr: 'mew'},
  {bits: 3, name: 0x7, attr: 'nf'},
]}
....

Description::
Store `vs3`-`vs3+7` to address in `rs1`

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vs8r_v.h[]
