== Vector Single-Width Integer Multiply Instructions

=== vmul.vv

Mnemonic::
--
    vmul.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x25, attr: 'vmul'},
]}
....

Description::
Signed multiply, returning low bits of product, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmul_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmul_vv_intrinsic.cpp[]
----
====


=== vmul.vx

Mnemonic::
--
    vmul.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x25, attr: 'vmul'},
]}
....

Description::
Signed multiply, returning low bits of product, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmul_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmul_vx_intrinsic.cpp[]
----
====


=== vmulh.vv

Mnemonic::
--
    vmulh.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'vmulh'},
]}
....

Description::
Signed multiply, returning high bits of product, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulh_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulh_vv_intrinsic.cpp[]
----
====


=== vmulh.vx

Mnemonic::
--
    vmulh.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'vmulh'},
]}
....

Description::
Signed multiply, returning high bits of product, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulh_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulh_vx_intrinsic.cpp[]
----
====


=== vmulhu.vv

Mnemonic::
--
    vmulhu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x24, attr: 'vmulhu'},
]}
....

Description::
Unsigned multiply, returning high bits of product, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulhu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulhu_vv_intrinsic.cpp[]
----
====


=== vmulhu.vx

Mnemonic::
--
    vmulhu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x24, attr: 'vmulhu'},
]}
....

Description::
Unsigned multiply, returning high bits of product, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulhu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulhu_vx_intrinsic.cpp[]
----
====


=== vmulhsu.vv

Mnemonic::
--
    vmulhsu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x26, attr: 'vmulhsu'},
]}
....

Description::
Signed(vs2)-Unsigned multiply, returning high bits of product, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulhsu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulhsu_vv_intrinsic.cpp[]
----
====


=== vmulhsu.vx

Mnemonic::
--
    vmulhsu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x26, attr: 'vmulhsu'},
]}
....

Description::
Signed(vs2)-Unsigned multiply, returning high bits of product, vector-scalar


== Vector Integer Divide Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmulhsu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmulhsu_vx_intrinsic.cpp[]
----
====


=== vdivu.vv

Mnemonic::
--
    vdivu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'vdivu'},
]}
....

Description::
Unsigned divide, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vdivu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vdivu_vv_intrinsic.cpp[]
----
====


=== vdivu.vx

Mnemonic::
--
    vdivu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'vdivu'},
]}
....

Description::
Unsigned divide, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vdivu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vdivu_vx_intrinsic.cpp[]
----
====


=== vdiv.vv

Mnemonic::
--
    vdiv.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'vdiv'},
]}
....

Description::
Signed divide, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vdiv_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vdiv_vv_intrinsic.cpp[]
----
====


=== vdiv.vx

Mnemonic::
--
    vdiv.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'vdiv'},
]}
....

Description::
Signed divide, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vdiv_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vdiv_vx_intrinsic.cpp[]
----
====


=== vremu.vv

Mnemonic::
--
    vremu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'vremu'},
]}
....

Description::
Unsigned remainder, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vremu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vremu_vv_intrinsic.cpp[]
----
====


=== vremu.vx

Mnemonic::
--
    vremu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'vremu'},
]}
....

Description::
Unsigned remainder, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vremu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vremu_vx_intrinsic.cpp[]
----
====


=== vrem.vv

Mnemonic::
--
    vrem.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'vrem'},
]}
....

Description::
Signed remainder, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrem_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vrem_vv_intrinsic.cpp[]
----
====


=== vrem.vx

Mnemonic::
--
    vrem.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'vrem'},
]}
....

Description::
Signed remainder, vector-scalar


== Vector Widening Integer Multiply Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrem_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vrem_vx_intrinsic.cpp[]
----
====


=== vwmul.vv

Mnemonic::
--
    vwmul.vv   vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3b, attr: 'vwmul'},
]}
....

Description::
Widening signed-integer multiply, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmul_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmul_vv_intrinsic.cpp[]
----
====


=== vwmul.vx

Mnemonic::
--
    vwmul.vx   vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3b, attr: 'vwmul'},
]}
....

Description::
Widening signed-integer multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmul_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmul_vx_intrinsic.cpp[]
----
====


=== vwmulu.vv

Mnemonic::
--
    vwmulu.vv  vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x38, attr: 'vwmulu'},
]}
....

Description::
Widening unsigned-integer multiply, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmulu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmulu_vv_intrinsic.cpp[]
----
====


=== vwmulu.vx

Mnemonic::
--
    vwmulu.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x38, attr: 'vwmulu'},
]}
....

Description::
Widening unsigned-integer multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmulu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmulu_vx_intrinsic.cpp[]
----
====


=== vwmulsu.vv

Mnemonic::
--
    vwmulsu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3a, attr: 'vwmulsu'},
]}
....

Description::
Widening signed(vs2)-unsigned integer multiply, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmulsu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmulsu_vv_intrinsic.cpp[]
----
====


=== vwmulsu.vx

Mnemonic::
--
    vwmulsu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3a, attr: 'vwmulsu'},
]}
....

Description::
Widening signed(vs2)-unsigned integer multiply, vector-scalar

== Vector Single-Width Integer Multiply-Add Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmulsu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmulsu_vx_intrinsic.cpp[]
----
====


=== vmacc.vv

Mnemonic::
--
    vmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2d, attr: 'vmacc'},
]}
....

Description::
Integer multiply-add, overwrite addend.
vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmacc_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmacc_vv_intrinsic.cpp[]
----
====


=== vmacc.vx

Mnemonic::
--
    vmacc.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2d, attr: 'vmacc'},
]}
....

Description::
Integer multiply-add, overwrite addend.
vd[i] = +(x[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmacc_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmacc_vx_intrinsic.cpp[]
----
====


=== vnmsac.vv

Mnemonic::
--
    vnmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'vnmsac'},
]}
....

Description::
Integer multiply-sub, overwrite minuend.
vd[i] = -(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnmsac_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnmsac_vv_intrinsic.cpp[]
----
====


=== vnmsac.vx

Mnemonic::
--
    vnmsac.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'vnmsac'},
]}
....

Description::
Integer multiply-sub, overwrite minuend.
vd[i] = -(x[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnmsac_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnmsac_vx_intrinsic.cpp[]
----
====


=== vmadd.vv

Mnemonic::
--
    vmadd.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x29, attr: 'vmadd'},
]}
....

Description::
Integer multiply-add, overwrite multiplicand.
vd[i] = (vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadd_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadd_vv_intrinsic.cpp[]
----
====


=== vmadd.vx

Mnemonic::
--
    vmadd.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x29, attr: 'vmadd'},
]}
....

Description::
Integer multiply-add, overwrite multiplicand.
vd[i] = (x[rs1] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmadd_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmadd_vx_intrinsic.cpp[]
----
====


=== vnmsub.vv

Mnemonic::
--
    vnmsub.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'vnmsub'},
]}
....

Description::
Integer multiply-sub, overwrite multiplicand.
vd[i] = -(vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnmsub_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnmsub_vv_intrinsic.cpp[]
----
====


=== vnmsub.vx

Mnemonic::
--
    vnmsub.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'vnmsub'},
]}
....

Description::
Integer multiply-sub, overwrite multiplicand.
vd[i] = -(x[rs1] * vd[i]) + vs2[i]


== Vector Widening Integer Multiply-Add Instructions

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vnmsub_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnmsub_vx_intrinsic.cpp[]
----
====


=== vwmaccu.vv

Mnemonic::
--
    vwmaccu.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3c, attr: 'vwmaccu'},
]}
....

Description::
Widening unsigned-integer multiply-add, overwrite addend.
vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmaccu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmaccu_vv_intrinsic.cpp[]
----
====


=== vwmaccu.vx

Mnemonic::
--
    vwmaccu.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3c, attr: 'vwmaccu'},
]}
....

Description::
Widening unsigned-integer multiply-add, overwrite addend.
vd[i] = +(x[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmaccu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmaccu_vx_intrinsic.cpp[]
----
====


=== vwmacc.vv

Mnemonic::
--
    vwmacc.vv  vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3d, attr: 'vwmacc'},
]}
....


Description::
Widening signed-integer multiply-add, overwrite addend.
vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmacc_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmacc_vv_intrinsic.cpp[]
----
====


=== vwmacc.vx

Mnemonic::
--
    vwmacc.vx  vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3d, attr: 'vwmacc'},
]}
....

Description::
Widening signed-integer multiply-add, overwrite addend.
vd[i] = +(x[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmacc_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmacc_vx_intrinsic.cpp[]
----
====


=== vwmaccsu.vv

Mnemonic::
--
    vwmaccsu.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3f, attr: 'vwmaccsu'},
]}
....

Description::
Widening signed-unsigned-integer multiply-add, overwrite addend.
vd[i] = +(signed(vs1[i]) * unsigned(vs2[i])) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmaccsu_vv.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmaccsu_vv_intrinsic.cpp[]
----
====


=== vwmaccsu.vx

Mnemonic::
--
    vwmaccsu.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3f, attr: 'vwmaccsu'},
]}
....

Description::
Widening signed-unsigned-integer multiply-add, overwrite addend.
vd[i] = +(signed(x[rs1]) * unsigned(vs2[i])) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmaccsu_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmaccsu_vx_intrinsic.cpp[]
----
====


=== vwmaccus.vx

Mnemonic::
--
    vwmaccus.vx vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3e, attr: 'vwmaccus'},
]}
....

Description::
Widening unsigned-signed-integer multiply-add, overwrite addend.
vd[i] = +(unsigned(x[rs1]) * signed(vs2[i])) + vd[i]


Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vwmaccus_vx.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vwmaccus_vx_intrinsic.cpp[]
----
====
