== Vector Fixed-Point Arithmetic Instructions

=== Vector Single-Width Saturating Add and Subtract

==== vsaddu.vv

Mnemonic::
--
    vsaddu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'funct6'},
]}
....

Description::
Saturating adds of unsigned integers, Vector-vector

==== vsaddu.vx

Mnemonic::
--
    vsaddu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'funct6'},
]}
....

Description::
Saturating adds of unsigned integers, vector-scalar

==== vsaddu.vi

Mnemonic::
--
    vsaddu.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'funct6'},
]}
....

Description::
Saturating adds of unsigned integers, vector-immediate

==== vsadd.vv

Mnemonic::
--
    vsadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'funct6'},
]}
....

Description::
Saturating adds of signed integers, Vector-vector

==== vsadd.vx

Mnemonic::
--
    vsadd.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'funct6'},
]}
....

Description::
Saturating adds of signed integers, vector-scalar

==== vsadd.vi

Mnemonic::
--
    vsadd.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'funct6'},
]}
....

Description::
Saturating adds of signed integers, vector-immediate

==== vssubu.vv

Mnemonic::
--
    vssubu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'funct6'},
]}
....

Description::
Saturating subtract of unsigned integers, Vector-vector

==== vssubu.vx

Mnemonic::
--
    vssubu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'funct6'},
]}
....

Description::
Saturating subtract of unsigned integers, vector-scalar

==== vssub.vv

Mnemonic::
--
    vssub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'funct6'},
]}
....

Description::
Saturating subtract of signed integers, Vector-vector

==== vssub.vx

Mnemonic::
--
    vssub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'funct6'},
]}
....

Description::
Saturating subtract of signed integers, vector-scalar


=== Vector Single-Width Averaging Add and Subtract

==== vaaddu.vv

Mnemonic::
--
    vaaddu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'funct6'},
]}
....

Description::
Averaging adds of unsigned integers, roundoff_unsigned(vs2[i] + vs1[i], 1)

==== vaaddu.vx

Mnemonic::
--
    vaaddu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'funct6'},
]}
....

Description::
Averaging adds of unsigned integers, roundoff_unsigned(vs2[i] + x[rs1], 1)

==== vaadd.vv

Mnemonic::
--
    vaadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'funct6'},
]}
....

Description::
Averaging adds of signed integers, roundoff_signed(vs2[i] + vs1[i], 1)

==== vaadd.vx

Mnemonic::
--
    vaadd.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'funct6'},
]}
....

Description::
Averaging adds of signed integers, roundoff_signed(vs2[i] + x[rs1], 1)

==== vasubu.vv

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'funct6'},
]}
....

Description::
Averaging subtract of unsigned integers, roundoff_unsigned(vs2[i] - vs1[i], 1)

==== vasubu.vx

Mnemonic::
--
    vasubu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'funct6'},
]}
....

Description::
Averaging subtract of unsigned integers, roundoff_unsigned(vs2[i] - x[rs1], 1)

==== vasub.vv

Mnemonic::
--
    vasub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0b, attr: 'funct6'},
]}
....

Description::
Averaging subtract of signed integers, roundoff_signed(vs2[i] - vs1[i], 1)

==== vasub.vx

Mnemonic::
--
    vasub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0b, attr: 'funct6'},
]}
....

Description::
Averaging subtract of signed integers, roundoff_signed(vs2[i] - x[rs1], 1)


=== Vector Single-Width Fractional Multiply with Rounding and Saturation

==== vsmul.vv

Mnemonic::
--
    vsmul.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'funct6'},
]}
....

Description::
Signed saturating and rounding fractional multiply
vd[i] = clip(roundoff_signed(vs2[i]*vs1[i], SEW-1))

==== vsmul.vx

Mnemonic::
--
    vsmul.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'funct6'},
]}
....

Description::
Signed saturating and rounding fractional multiply
vd[i] = clip(roundoff_signed(vs2[i]*x[rs1], SEW-1))


=== Vector Single-Width Scaling Shift Instructions

==== vssrl.vv
Mnemonic::
--
    vssrl.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'funct6'},
]}
....

Description::
Scaling shift right logical.
vd[i] = roundoff_unsigned(vs2[i], vs1[i])

==== vssrl.vx

Mnemonic::
--
    vssrl.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'funct6'},
]}
....

Description::
Scaling shift right logical.

vd[i] = roundoff_unsigned(vs2[i], x[rs1])

==== vssrl.vi
Mnemonic::
--
    vssrl.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'funct6'},
]}
....

Description::
Scaling shift right logical.

vd[i] = roundoff_unsigned(vs2[i], uimm)

==== vssra.vv
Mnemonic::
--
    vssra.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'funct6'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i],vs1[i])

==== vssra.vx
Mnemonic::
--
    vssra.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'funct6'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i], x[rs1])

==== vssra.vi

Mnemonic::
--
    vssra.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'funct6'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i], uimm)

=== Vector Narrowing Fixed-Point Clip Instructions

==== vnclipu.wv
Mnemonic::
--
    vnclipu.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'funct6'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], vs1[i]))

==== vnclipu.wx
Mnemonic::
--
    vnclipu.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'funct6'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], x[rs1]))

==== vnclipu.wi
Mnemonic::
--
    vnclipu.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'funct6'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], uimm))

==== vnclip.wv
Mnemonic::
--
    vnclip.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'funct6'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], vs1[i]))

==== vnclip.wx
Mnemonic::
--
    vnclip.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'funct6'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], x[rs1]))

==== vnclip.wi
Mnemonic::
--
    vnclip.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'funct6'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], uimm))
