== Vector Fixed-Point Arithmetic Instructions

=== Vector Single-Width Saturating Add and Subtract

=== vsaddu.vv

Mnemonic::
--
    vsaddu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'vsaddu'},
]}
....

Description::
Saturating adds of unsigned integers, Vector-vector

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsaddu_vv_intrinsic.cpp[]
----
====


=== vsaddu.vx

Mnemonic::
--
    vsaddu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'vsaddu'},
]}
....

Description::
Saturating adds of unsigned integers, vector-scalar

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsaddu_vx_intrinsic.cpp[]
----
====


=== vsaddu.vi

Mnemonic::
--
    vsaddu.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'vsaddu'},
]}
....

Description::
Saturating adds of unsigned integers, vector-immediate

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsaddu_vi_intrinsic.cpp[]
----
====


=== vsadd.vv

Mnemonic::
--
    vsadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'vsadd'},
]}
....

Description::
Saturating adds of signed integers, Vector-vector

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsadd_vv_intrinsic.cpp[]
----
====


=== vsadd.vx

Mnemonic::
--
    vsadd.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'vsadd'},
]}
....

Description::
Saturating adds of signed integers, vector-scalar

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsadd_vx_intrinsic.cpp[]
----
====


=== vsadd.vi

Mnemonic::
--
    vsadd.vi vd, vs2, imm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'vsadd'},
]}
....

Description::
Saturating adds of signed integers, vector-immediate

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsadd_vi_intrinsic.cpp[]
----
====


=== vssubu.vv

Mnemonic::
--
    vssubu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'vssubu'},
]}
....

Description::
Saturating subtract of unsigned integers, Vector-vector

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssubu_vv_intrinsic.cpp[]
----
====


=== vssubu.vx

Mnemonic::
--
    vssubu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x22, attr: 'vssubu'},
]}
....

Description::
Saturating subtract of unsigned integers, vector-scalar

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssubu_vx_intrinsic.cpp[]
----
====


=== vssub.vv

Mnemonic::
--
    vssub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'vssub'},
]}
....

Description::
Saturating subtract of signed integers, Vector-vector

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssub_vv_intrinsic.cpp[]
----
====


=== vssub.vx

Mnemonic::
--
    vssub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x23, attr: 'vssub'},
]}
....

Description::
Saturating subtract of signed integers, vector-scalar


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssub_vx_intrinsic.cpp[]
----
====


=== Vector Single-Width Averaging Add and Subtract

=== vaaddu.vv

Mnemonic::
--
    vaaddu.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'vaaddu'},
]}
....

Description::
Averaging adds of unsigned integers, roundoff_unsigned(vs2[i] + vs1[i], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vaaddu_vv_intrinsic.cpp[]
----
====


=== vaaddu.vx

Mnemonic::
--
    vaaddu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'vaaddu'},
]}
....

Description::
Averaging adds of unsigned integers, roundoff_unsigned(vs2[i] + x[rs1], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vaaddu_vx_intrinsic.cpp[]
----
====


=== vaadd.vv

Mnemonic::
--
    vaadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'vaadd'},
]}
....

Description::
Averaging adds of signed integers, roundoff_signed(vs2[i] + vs1[i], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vaadd_vv_intrinsic.cpp[]
----
====


=== vaadd.vx

Mnemonic::
--
    vaadd.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'vaadd'},
]}
....

Description::
Averaging adds of signed integers, roundoff_signed(vs2[i] + x[rs1], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vaadd_vx_intrinsic.cpp[]
----
====


=== vasubu.vv

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'vasubu'},
]}
....

Description::
Averaging subtract of unsigned integers, roundoff_unsigned(vs2[i] - vs1[i], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vasubu_vv_intrinsic.cpp[]
----
====


=== vasubu.vx

Mnemonic::
--
    vasubu.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'vasubu'},
]}
....

Description::
Averaging subtract of unsigned integers, roundoff_unsigned(vs2[i] - x[rs1], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vasubu_vx_intrinsic.cpp[]
----
====


=== vasub.vv

Mnemonic::
--
    vasub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0b, attr: 'vasub'},
]}
....

Description::
Averaging subtract of signed integers, roundoff_signed(vs2[i] - vs1[i], 1)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vasub_vv_intrinsic.cpp[]
----
====


=== vasub.vx

Mnemonic::
--
    vasub.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0b, attr: 'vasub'},
]}
....

Description::
Averaging subtract of signed integers, roundoff_signed(vs2[i] - x[rs1], 1)


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vasub_vx_intrinsic.cpp[]
----
====


=== Vector Single-Width Fractional Multiply with Rounding and Saturation

=== vsmul.vv

Mnemonic::
--
    vsmul.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'vsmul'},
]}
....

Description::
Signed saturating and rounding fractional multiply
vd[i] = clip(roundoff_signed(vs2[i]*vs1[i], SEW-1))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsmul_vv_intrinsic.cpp[]
----
====


=== vsmul.vx

Mnemonic::
--
    vsmul.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'vsmul'},
]}
....

Description::
Signed saturating and rounding fractional multiply
vd[i] = clip(roundoff_signed(vs2[i]*x[rs1], SEW-1))


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vsmul_vx_intrinsic.cpp[]
----
====


=== Vector Single-Width Scaling Shift Instructions

=== vssrl.vv
Mnemonic::
--
    vssrl.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'vssrl'},
]}
....

Description::
Scaling shift right logical.
vd[i] = roundoff_unsigned(vs2[i], vs1[i])

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssrl_vv_intrinsic.cpp[]
----
====


=== vssrl.vx

Mnemonic::
--
    vssrl.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'vssrl'},
]}
....

Description::
Scaling shift right logical.

vd[i] = roundoff_unsigned(vs2[i], x[rs1])

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssrl_vx_intrinsic.cpp[]
----
====


=== vssrl.vi
Mnemonic::
--
    vssrl.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'vssrl'},
]}
....

Description::
Scaling shift right logical.

vd[i] = roundoff_unsigned(vs2[i], uimm)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssrl_vi_intrinsic.cpp[]
----
====


=== vssra.vv
Mnemonic::
--
    vssra.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'vssra'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i],vs1[i])

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssra_vv_intrinsic.cpp[]
----
====


=== vssra.vx
Mnemonic::
--
    vssra.vx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'vssra'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i], x[rs1])

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssra_vx_intrinsic.cpp[]
----
====


=== vssra.vi

Mnemonic::
--
    vssra.vi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'vssra'},
]}
....

Description::
Scaling shift right arithmetic.

vd[i] = roundoff_signed(vs2[i], uimm)

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vssra_vi_intrinsic.cpp[]
----
====


=== Vector Narrowing Fixed-Point Clip Instructions

=== vnclipu.wv
Mnemonic::
--
    vnclipu.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'vnclipu'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], vs1[i]))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclipu_wv_intrinsic.cpp[]
----
====


=== vnclipu.wx
Mnemonic::
--
    vnclipu.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'vnclipu'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], x[rs1]))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclipu_wx_intrinsic.cpp[]
----
====


=== vnclipu.wi
Mnemonic::
--
    vnclipu.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'vnclipu'},
]}
....

Description::
Narrowing unsigned clip.

vd[i] = clip(roundoff_unsigned(vs2[i], uimm))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclipu_wi_intrinsic.cpp[]
----
====


=== vnclip.wv
Mnemonic::
--
    vnclip.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'vnclip'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], vs1[i]))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclip_wv_intrinsic.cpp[]
----
====


=== vnclip.wx
Mnemonic::
--
    vnclip.wx vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'vnclip'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], x[rs1]))

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclip_wx_intrinsic.cpp[]
----
====


=== vnclip.wi
Mnemonic::
--
    vnclip.wi vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'vnclip'},
]}
....

Description::
Narrowing signed clip.

vd[i] = clip(roundoff_signed(vs2[i], uimm))


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclip_wi_intrinsic.cpp[]
----
====


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vnclip_v_intrinsic.cpp[]
----
====
