== Vector Permutation Instructions

== Integer Scalar Move Instructions

=== vmv.x.s

Mnemonic::
--
    vmv.x.s rd, vs2
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'rd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x0, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x10, attr: 'VWXUNARY0'},
]}
....

Description::
x[rd] = vs2[0] (vs1=0)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv_x_s.h[]

Intrinsics::
[source,cpp]
--
int8_t vmv_x_s_i8m1_i8 (vint8m1_t vs2, size_t vl);
int8_t vmv_x_s_i8m2_i8 (vint8m2_t vs2, size_t vl);
int8_t vmv_x_s_i8m4_i8 (vint8m4_t vs2, size_t vl);
int8_t vmv_x_s_i8m8_i8 (vint8m8_t vs2, size_t vl);
--

=== vmv.s.x

Mnemonic::
--
    vmv.s.x vd, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 0x00, attr: 'vs2'},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x10, attr: 'VRXUNARY0'},
]}
....

Description::
vd[0] = x[rs1] (vs2=0)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv_s_x.h[]

Intrinsics::
[%collapsible]
====
[source,cpp]
--
vint8mf8_t __riscv_vmv_s_x_i8mf8 (int8_t src, size_t vl);
vint8mf4_t __riscv_vmv_s_x_i8mf4 (int8_t src, size_t vl);
vint8mf2_t __riscv_vmv_s_x_i8mf2 (int8_t src, size_t vl);
vint8m1_t __riscv_vmv_s_x_i8m1 (int8_t src, size_t vl);
vint8m2_t __riscv_vmv_s_x_i8m2 (int8_t src, size_t vl);
vint8m4_t __riscv_vmv_s_x_i8m4 (int8_t src, size_t vl);
vint8m8_t __riscv_vmv_s_x_i8m8 (int8_t src, size_t vl);
vint16mf4_t __riscv_vmv_s_x_i16mf4 (int16_t src, size_t vl);
vint16mf2_t __riscv_vmv_s_x_i16mf2 (int16_t src, size_t vl);
vint16m1_t __riscv_vmv_s_x_i16m1 (int16_t src, size_t vl);
vint16m2_t __riscv_vmv_s_x_i16m2 (int16_t src, size_t vl);
vint16m4_t __riscv_vmv_s_x_i16m4 (int16_t src, size_t vl);
vint16m8_t __riscv_vmv_s_x_i16m8 (int16_t src, size_t vl);
vint32mf2_t __riscv_vmv_s_x_i32mf2 (int32_t src, size_t vl);
vint32m1_t __riscv_vmv_s_x_i32m1 (int32_t src, size_t vl);
vint32m2_t __riscv_vmv_s_x_i32m2 (int32_t src, size_t vl);
vint32m4_t __riscv_vmv_s_x_i32m4 (int32_t src, size_t vl);
vint32m8_t __riscv_vmv_s_x_i32m8 (int32_t src, size_t vl);
vint64m1_t __riscv_vmv_s_x_i64m1 (int64_t src, size_t vl);
vint64m2_t __riscv_vmv_s_x_i64m2 (int64_t src, size_t vl);
vint64m4_t __riscv_vmv_s_x_i64m4 (int64_t src, size_t vl);
vint64m8_t __riscv_vmv_s_x_i64m8 (int64_t src, size_t vl);
vuint8mf8_t __riscv_vmv_s_x_u8mf8 (uint8_t src, size_t vl);
vuint8mf4_t __riscv_vmv_s_x_u8mf4 (uint8_t src, size_t vl);
vuint8mf2_t __riscv_vmv_s_x_u8mf2 (uint8_t src, size_t vl);
vuint8m1_t __riscv_vmv_s_x_u8m1 (uint8_t src, size_t vl);
vuint8m2_t __riscv_vmv_s_x_u8m2 (uint8_t src, size_t vl);
vuint8m4_t __riscv_vmv_s_x_u8m4 (uint8_t src, size_t vl);
vuint8m8_t __riscv_vmv_s_x_u8m8 (uint8_t src, size_t vl);
vuint16mf4_t __riscv_vmv_s_x_u16mf4 (uint16_t src, size_t vl);
vuint16mf2_t __riscv_vmv_s_x_u16mf2 (uint16_t src, size_t vl);
vuint16m1_t __riscv_vmv_s_x_u16m1 (uint16_t src, size_t vl);
vuint16m2_t __riscv_vmv_s_x_u16m2 (uint16_t src, size_t vl);
vuint16m4_t __riscv_vmv_s_x_u16m4 (uint16_t src, size_t vl);
vuint16m8_t __riscv_vmv_s_x_u16m8 (uint16_t src, size_t vl);
vuint32mf2_t __riscv_vmv_s_x_u32mf2 (uint32_t src, size_t vl);
vuint32m1_t __riscv_vmv_s_x_u32m1 (uint32_t src, size_t vl);
vuint32m2_t __riscv_vmv_s_x_u32m2 (uint32_t src, size_t vl);
vuint32m4_t __riscv_vmv_s_x_u32m4 (uint32_t src, size_t vl);
vuint32m8_t __riscv_vmv_s_x_u32m8 (uint32_t src, size_t vl);
vuint64m1_t __riscv_vmv_s_x_u64m1 (uint64_t src, size_t vl);
vuint64m2_t __riscv_vmv_s_x_u64m2 (uint64_t src, size_t vl);
vuint64m4_t __riscv_vmv_s_x_u64m4 (uint64_t src, size_t vl);
vuint64m8_t __riscv_vmv_s_x_u64m8 (uint64_t src, size_t vl);
--
====

== Floating-Point Scalar Move Instructions

=== vfmv.f.s

Mnemonic::
--
    vfmv.f.s rd, vs2
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x0, attr: 'vs1'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x10, attr: 'VWFUNARY0'},
]}
....

Description::
f[rd] = vs2[0] (rs1=0)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmv_f_s.h[]

Intrinsics::
[source,cpp]
--
float16_t __riscv_vfmv_f_s_f16mf4_f16 (vfloat16mf4_t src);
float16_t __riscv_vfmv_f_s_f16mf2_f16 (vfloat16mf2_t src);
float16_t __riscv_vfmv_f_s_f16m1_f16 (vfloat16m1_t src);
float16_t __riscv_vfmv_f_s_f16m2_f16 (vfloat16m2_t src);
float16_t __riscv_vfmv_f_s_f16m4_f16 (vfloat16m4_t src);
float16_t __riscv_vfmv_f_s_f16m8_f16 (vfloat16m8_t src);
float32_t __riscv_vfmv_f_s_f32mf2_f32 (vfloat32mf2_t src);
float32_t __riscv_vfmv_f_s_f32m1_f32 (vfloat32m1_t src);
float32_t __riscv_vfmv_f_s_f32m2_f32 (vfloat32m2_t src);
float32_t __riscv_vfmv_f_s_f32m4_f32 (vfloat32m4_t src);
float32_t __riscv_vfmv_f_s_f32m8_f32 (vfloat32m8_t src);
float64_t __riscv_vfmv_f_s_f64m1_f64 (vfloat64m1_t src);
float64_t __riscv_vfmv_f_s_f64m2_f64 (vfloat64m2_t src);
float64_t __riscv_vfmv_f_s_f64m4_f64 (vfloat64m4_t src);
float64_t __riscv_vfmv_f_s_f64m8_f64 (vfloat64m8_t src);
--

=== vfmv.s.f

Mnemonic::
--
    vfmv.s.f vd, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 0x00, attr: 'vs2'},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x10, attr: 'VRFUNARY0'},
]}
....

Description::
vd[0] = f[rs1] (vs2=0)

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmv_s_f.h[]

Intrinsics::
[source,cpp]
--
vfloat16mf4_t __riscv_vfmv_s_f_f16mf4 (float16_t src, size_t vl);
vfloat16mf2_t __riscv_vfmv_s_f_f16mf2 (float16_t src, size_t vl);
vfloat16m1_t __riscv_vfmv_s_f_f16m1 (float16_t src, size_t vl);
vfloat16m2_t __riscv_vfmv_s_f_f16m2 (float16_t src, size_t vl);
vfloat16m4_t __riscv_vfmv_s_f_f16m4 (float16_t src, size_t vl);
vfloat16m8_t __riscv_vfmv_s_f_f16m8 (float16_t src, size_t vl);
vfloat32mf2_t __riscv_vfmv_s_f_f32mf2 (float32_t src, size_t vl);
vfloat32m1_t __riscv_vfmv_s_f_f32m1 (float32_t src, size_t vl);
vfloat32m2_t __riscv_vfmv_s_f_f32m2 (float32_t src, size_t vl);
vfloat32m4_t __riscv_vfmv_s_f_f32m4 (float32_t src, size_t vl);
vfloat32m8_t __riscv_vfmv_s_f_f32m8 (float32_t src, size_t vl);
vfloat64m1_t __riscv_vfmv_s_f_f64m1 (float64_t src, size_t vl);
vfloat64m2_t __riscv_vfmv_s_f_f64m2 (float64_t src, size_t vl);
vfloat64m4_t __riscv_vfmv_s_f_f64m4 (float64_t src, size_t vl);
vfloat64m8_t __riscv_vfmv_s_f_f64m8 (float64_t src, size_t vl);
--


== Vector Slide Instructions

=== vslideup.vx

Mnemonic::
--
    vslideup.vx     vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0e, attr: 'vslideup'},
]}
....

Description::
vd[i+x[rs1]] = vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslideup_vx.h[]

Intrinsics::
[source,cpp]
--

--

=== vslideup.vi

Mnemonic::
--
    vslideup.vi     vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0e, attr: 'vslideup'},
]}
....

Description::
vd[i+uimm] = vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslideup_vi.h[]

Intrinsics::
[source,cpp]
--

--

=== vslidedown.vx

Mnemonic::
--
    vslidedown.vx   vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0f, attr: 'vslidedown'},
]}
....

Description::
vd[i] = vs2[i+x[rs1]]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslidedown_vx.h[]

Intrinsics::
[source,cpp]
--
--

=== vslidedown.vi

Mnemonic::
--
    vslidedown.vi   vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0f, attr: 'vslidedown'},
]}
....

Description::
vd[i] = vs2[i+uimm]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslidedown_vi.h[]

Intrinsics::
[source,cpp]
--
--

=== vslide1up.vx

Mnemonic::
--
    vslide1up.vx    vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0e, attr: 'vslide1up'},
]}
....

Description::
vd[0]=x[rs1], vd[i+1] = vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslide1up_vx.h[]

Intrinsics::
[source,cpp]
--
--

=== vfslide1up.vf

Mnemonic::
--
    vfslide1up.vf   vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0e, attr: 'vfslide1up'},
]}
....

Description::
vd[0]=f[rs1], vd[i+1] = vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfslide1up_vf.h[]

Intrinsics::
[source,cpp]
--
--

=== vslide1down.vx

Mnemonic::
--
    vslide1down.vx  vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVX'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 6},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0f, attr: 'vslide1down'},
]}
....

Description::
vd[i] = vs2[i+1], vd[vl-1]=x[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vslide1down_vx.h[]

Intrinsics::
[source,cpp]
--
--

=== vfslide1down.vf

Mnemonic::
--
    vfslide1down.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0f, attr: 'vfslide1down'},
]}
....

Description::
vd[i] = vs2[i+1], vd[vl-1]=f[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfslide1down_vf.h[]

Intrinsics::
[source,cpp]
--
--


== Vector Register Gather Instructions

=== vrgather.vv

Mnemonic::
--
    vrgather.vv     vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0c, attr: 'vrgather'},
]}
....

Description::
vd[i] = (vs1[i] >= VLMAX) ? 0 : vs2[vs1[i]];

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrgather_vv.h[]

Intrinsics::
[source,cpp]
--
--


=== vrgatherei16.vv

Mnemonic::
--
    vrgatherei16.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVV'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 0},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0e, attr: 'vrgatherei16'},
]}
....

Description::
vd[i] = (vs1[i] >= VLMAX) ? 0 : vs2[vs1[i]];

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrgatherei16_vv.h[]

Intrinsics::
[source,cpp]
--
--

=== vrgather.vx

Mnemonic::
--
    vrgather.vx     vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPIVX'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 4},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0c, attr: 'vrgather'},
]}
....

Description::
vd[i] = (x[rs1] >= VLMAX) ? 0 : vs2[x[rs1]]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrgather_vx.h[]

Intrinsics::
[source,cpp]
--
--

=== vrgather.vi

Mnemonic::
--
    vrgather.vi     vd, vs2, uimm, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 5, name: 'imm[4:0]', type: 5},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0c, attr: 'vrgather'},
]}
....

Description::
vd[i] =  (uimm >= VLMAX)  ? 0 : vs2[uimm]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vrgather_vi.h[]

Intrinsics::
[source,cpp]
--
--


== Vector Compress Instruction

=== vcompress.vm

Mnemonic::
--
    vcompress.vm vd, vs2, vs1  #
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x17, attr: 'vcompress'},
]}
....

Description::
Compress into vd elements of vs2 where vs1 is enabled

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vcompress_vm.h[]

== Whole Vector Register Move

=== vmv<nr>r.v

Mnemonic::
--
    vmv1r.v vd, vs2
    vmv2r.v vd, vs2
    vmv4r.v vd, vs2
    vmv8r.v vd, vs2
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: ['OPIVI']},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 3},
  {bits: 2, name: 0},
  {bits: 3, name: 'nf-1', attr: 'nf'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 6, name: 0x27, attr: 'vmv<nr>r'},
]}
....

Description::

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv1r.h[]
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv2r.h[]
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv4r.h[]
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmv8r.h[]

Intrinsics::
[source,cpp]
--
--
