== Vector Mask Instructions

=== Vector Mask-Register Logical Instructions

=== vmand.mm

Mnemonic::
--
    vmand.mm vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x19, attr: 'vmand'},
]}
....

Description::
--
    vd.mask[i] =   vs2.mask[i] &&  vs1.mask[i]
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmand_mm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmand_mm_intrinsic.cpp[]
----
====


=== vmnand.mm

Mnemonic::
--
    vmnand.mm vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1d, attr: 'vmnand'},
]}
....

Description::
--
    vd.mask[i] = !(vs2.mask[i] &&  vs1.mask[i])
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmnand_mm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmnand_mm_intrinsic.cpp[]
----
====


=== vmandn.mm

Mnemonic::
--
    vmandn.mm vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x18, attr: 'vmandn'},
]}
....

Description::
--
    vd.mask[i] =   vs2.mask[i] && !vs1.mask[i]
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmandn_mm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmandn_mm_intrinsic.cpp[]
----
====


=== vmxor.mm

Mnemonic::
--
    vmxor.mm  vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1b, attr: 'vmxor'},
]}
....

Description::
--
    vd.mask[i] =   vs2.mask[i] ^^  vs1.mask[i]
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmxor_mm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmxor_mm_intrinsic.cpp[]
----
====


=== vmor.mm

Mnemonic::
--
    vmor.mm  vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1a, attr: 'vmor'},
]}
....

Description::
--
    vd.mask[i] =   vs2.mask[i] ||  vs1.mask[i]
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmor_mm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmor_mm_intrinsic.cpp[]
----
====


=== vmnor.mm

Mnemonic::
--
    vmnor.mm  vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1e, attr: 'vmnor'},
]}
....

Description::
--
    vd.mask[i] = !(vs2.mask[i] ||  vs1.mask[i])
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmnor_mm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmnor_mm_intrinsic.cpp[]
----
====


=== vmorn.mm

Mnemonic::
--
    vmorn.mm  vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1c, attr: 'vmorn'},
]}
....

Description::
--
    vd.mask[i] =   vs2.mask[i] || !vs1.mask[i]
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmorn_mm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmorn_mm_intrinsic.cpp[]
----
====


=== vmxnor.mm

Mnemonic::
--
    vmxnor.mm vd, vs2, vs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1f, attr: 'vmxnor'},
]}
....

Description::
--
    vd.mask[i] = !(vs2.mask[i] ^^  vs1.mask[i])
--

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmxnor_mm.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmxnor_mm_intrinsic.cpp[]
----
====


=== vcpop.m

Mnemonic::
--
    vcpop.m rd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x08, attr: 'vcpop'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x00, attr: 'VWXUNARY0'},
]}
....

Description::
Vector count population in mask

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vcpop_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vcpop_m_intrinsic.cpp[]
----
====


=== vfirst.m

Mnemonic::
--
    vfirst.m rd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x09, attr: 'vfirst'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x00, attr: 'VWXUNARY0'},
]}
....

Description::
find-first-set mask bit

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfirst_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfirst_m_intrinsic.cpp[]
----
====


=== vmsbf.m

Mnemonic::
--
    vmsbf.m vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x01, attr: 'vmsbf'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x14, attr: 'VMUNARY0'},
]}
....

Description::
set-before-first mask bit

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsbf_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsbf_m_intrinsic.cpp[]
----
====


=== vmsif.m

Mnemonic::
--
    vmsif.m vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x03, attr: 'vmsif'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x14, attr: 'VMUNARY0'},
]}
....

Description::
set-including-first mask bit

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsif_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsif_m_intrinsic.cpp[]
----
====


=== vmsof.m

Mnemonic::
--
    vmsof.m vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x02, attr: 'vmsof'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x14, attr: 'VMUNARY0'},
]}
....

Description::
set-only-first mask bit

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmsof_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmsof_m_intrinsic.cpp[]
----
====


=== viota.m

Mnemonic::
--
    viota.m vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x80, attr: 'viota'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x14, attr: 'VMUNARY0'},
]}
....

Desciption::
Vector Iota Instruction

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/viota_m.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/viota_m_intrinsic.cpp[]
----
====


=== vid.v

Mnemonic::
--
    vid.v vd, vm  # Write element ID to destination.
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPMVV'},
  {bits: 5, name: 'vd', type: 7},
  {bits: 3, name: 2},
  {bits: 5, name: 0x81, attr: 'vid'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x14, attr: 'VMUNARY0'},
]}
....

Description::
Vector Element Index

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vid_v.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vid_v_intrinsic.cpp[]
----
====
