== Vector Floating-Point Instructions

=== Vector Single-Width Floating-Point Add/Subtract Instructions

=== vfadd.vv
Mnemonic::
--
	vfadd.vv vd, vs2, vs1, vm
--

Description::
Floating-point add, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfadd_vv.h[]

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x00, attr: 'funct6'},
]}
....

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfadd_vv_intrinsic.cpp[]
----
====


=== vfadd.vf
Mnemonic::
--
	vfadd.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x00, attr: 'funct6'},
]}
....

Description::
Floating-point add, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfadd_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfadd_vf_intrinsic.cpp[]
----
====


=== vfsub.vv
Mnemonic::
--
	vfsub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x02, attr: 'funct6'},
]}
....

Description::
Floating-point subtract, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsub_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsub_vv_intrinsic.cpp[]
----
====


=== vfsub.vf
Mnemonic::
--
	vfsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x02, attr: 'funct6'},
]}
....

Description::
Floating-point subtract, Vector-scalar vd[i] = vs2[i] - f[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsub_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsub_vf_intrinsic.cpp[]
----
====


=== vfrsub.vf
Mnemonic::
--
	vfrsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x27, attr: 'funct6'},
]}
....

Description::
Floating-point subtract, Scalar-vector vd[i] = f[rs1] - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrsub_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfrsub_vf_intrinsic.cpp[]
----
====


=== Vector Widening Floating-Point Add/Subtract Instructions


=== vfwadd.vv
Mnemonic::
--
	vfwadd.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x30, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwadd_vv_intrinsic.cpp[]
----
====


=== vfwadd.vf
Mnemonic::
--
	vfwadd.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x30, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwadd_vf_intrinsic.cpp[]
----
====


=== vfwsub.vv
Mnemonic::
--
	vfwsub.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x32, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsb_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwsub_vv_intrinsic.cpp[]
----
====


=== vfwsub.vf
Mnemonic::
--
	vfwsub.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x32, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwsub_vf_intrinsic.cpp[]
----
====


=== vfwadd.wv
Mnemonic::
--
	vfwadd.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x34, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_wv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwadd_wv_intrinsic.cpp[]
----
====


=== vfwadd.wf
Mnemonic::
--
	vfwadd.wf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x34, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwadd_wf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwadd_wf_intrinsic.cpp[]
----
====


=== vfwsub.wv
Mnemonic::
--
	vfwsub.wv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x36, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_wf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwsub_wv_intrinsic.cpp[]
----
====


=== vfwsub.wf
Mnemonic::
--
	vfwsub.wf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x36, attr: 'funct6'},
]}
....

Description::
Widening FP add/subtract, 2*SEW = 2*SEW +/- SEW, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwsub_wf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwsub_wf_intrinsic.cpp[]
----
====


=== Vector Single-Width Floating-Point Multiply/Divide Instructions


=== vfmul.vv
Mnemonic::
--
	vfmul.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x24, attr: 'funct6'},
]}
....

Description::
Floating-point multiply, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmul_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmul_vv_intrinsic.cpp[]
----
====


=== vfmul.vf
Mnemonic::
--
	vfmul.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x24, attr: 'funct6'},
]}
....

Description::
Floating-point multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmul_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmul_vf_intrinsic.cpp[]
----
====


=== vfdiv.vv
Mnemonic::
--
	vfdiv.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 'funct6'},
]}
....

Description::
Floating-point divide, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfdiv_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfdiv_vv_intrinsic.cpp[]
----
====


=== vfdiv.vf
Mnemonic::
--
	vfdiv.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x20, attr: 'funct6'},
]}
....

Description::
Floating-point divide, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfdiv_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfdiv_vf_intrinsic.cpp[]
----
====


=== vfrdiv.vf
Mnemonic::
--
	vfrdiv.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x21, attr: 'funct6'},
]}
....

Description::
Reverse floating-point divide vector = scalar / vector, scalar-vector, vd[i] = f[rs1]/vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrdiv_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfrdiv_vf_intrinsic.cpp[]
----
====


=== Vector Widening Floating-Point Multiply

=== vfwmul.vv
Mnemonic::
--
	vfwmul.vv    vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x38, attr: 'funct6'},
]}
....

Description::
Widening floating-point multiply, vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmul_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmul_vv_intrinsic.cpp[]
----
====


=== vfwmul.vf
Mnemonic::
--
	vfwmul.vf    vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x38, attr: 'funct6'},
]}
....

Description::
Widening floating-point multiply, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmul_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmul_vf_intrinsic.cpp[]
----
====


=== Vector Single-Width Floating-Point Fused Multiply-Add Instructions

=== vfmacc.vv
Mnemonic::
--
	vfmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2c, attr: 'funct6'},
]}
....

Description::
FP multiply-accumulate, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmacc_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmacc_vv_intrinsic.cpp[]
----
====


=== vfmacc.vf
Mnemonic::
--
	vfmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2c, attr: 'funct6'},
]}
....

Description::
FP multiply-accumulate, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmacc_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmacc_vf_intrinsic.cpp[]
----
====


=== vfnmacc.vv
Mnemonic::
--
	vfnmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2d, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-accumulate), overwrites subtrahend, vd[i] = -(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmacc_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmacc_vv_intrinsic.cpp[]
----
====


=== vfnmacc.vf
Mnemonic::
--
	vfnmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2d, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-accumulate), overwrites subtrahend, vd[i] = -(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmacc_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmacc_vf_intrinsic.cpp[]
----
====


=== vfmsac.vv
Mnemonic::
--
	vfmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'funct6'},
]}
....

Description::
FP multiply-subtract-accumulator, overwrites subtrahend, vd[i] = +(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsac_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmsac_vv_intrinsic.cpp[]
----
====


=== vfmsac.vf
Mnemonic::
--
	vfmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2e, attr: 'funct6'},
]}
....

Description::
FP multiply-subtract-accumulator, overwrites subtrahend, vd[i] = +(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsac_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmsac_vf_intrinsic.cpp[]
----
====


=== vfnmsac.vv
Mnemonic::
--
	vfnmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-subtract-accumulator), overwrites minuend, vd[i] = -(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsac_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmsac_vv_intrinsic.cpp[]
----
====


=== vfnmsac.vf
Mnemonic::
--
	vfnmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2f, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-subtract-accumulator), overwrites minuend, vd[i] = -(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsac_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmsac_vf_intrinsic.cpp[]
----
====


=== vfmadd.vv
Mnemonic::
--
	vfmadd.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x28, attr: 'funct6'},
]}
....

Description::
FP multiply-add, overwrites multiplicand, vd[i] = +(vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmadd_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmadd_vv_intrinsic.cpp[]
----
====


=== vfmadd.vf
Mnemonic::
--
	vfmadd.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x28, attr: 'funct6'},
]}
....

Description::
FP multiply-add, overwrites multiplicand, vd[i] = +(f[rs1] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmadd_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmadd_vf_intrinsic.cpp[]
----
====


=== vfnmadd.vv
Mnemonic::
--
	vfnmadd.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x29, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-add), overwrites multiplicand, vd[i] = -(vs1[i] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmadd_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmadd_vv_intrinsic.cpp[]
----
====


=== vfnmadd.vf
Mnemonic::
--
	vfnmadd.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x29, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-add), overwrites multiplicand, vd[i] = -(f[rs1] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmadd_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmadd_vf_intrinsic.cpp[]
----
====


=== vfmsub.vv
Mnemonic::
--
	vfmsub.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'funct6'},
]}
....

Description::
FP multiply-sub, overwrites multiplicand, vd[i] = +(vs1[i] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsub_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmsub_vv_intrinsic.cpp[]
----
====


=== vfmsub.vf
Mnemonic::
--
	vfmsub.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2a, attr: 'funct6'},
]}
....

Description::
FP multiply-sub, overwrites multiplicand, vd[i] = +(f[rs1] * vd[i]) - vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmsub_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmsub_vf_intrinsic.cpp[]
----
====


=== vfnmsub.vv
Mnemonic::
--
	vfnmsub.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-sub), overwrites multiplicand, vd[i] = -(vs1[i] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsub_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmsub_vv_intrinsic.cpp[]
----
====


=== vfnmsub.vf
Mnemonic::
--
	vfnmsub.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x2b, attr: 'funct6'},
]}
....

Description::
FP negate-(multiply-sub), overwrites multiplicand, vd[i] = -(f[rs1] * vd[i]) + vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfnmsub_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfnmsub_vf_intrinsic.cpp[]
----
====


=== Vector Widening Floating-Point Fused Multiply-Add Instructions



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfwmacc.vv
Mnemonic::
--
	vfwmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3c, attr: 'funct6'},
]}
....

Description::
FP widening multiply-accumulate, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmacc_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmacc_vv_intrinsic.cpp[]
----
====


=== vfwmacc.vf
Mnemonic::
--
	vfwmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3c, attr: 'funct6'},
]}
....

Description::
FP widening multiply-accumulate, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmacc_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmacc_vf_intrinsic.cpp[]
----
====


=== vfwnmacc.vv
Mnemonic::
--
	vfwnmacc.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3d, attr: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-accumulate), overwrites addend, vd[i] = -(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmacc_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwnmacc_vv_intrinsic.cpp[]
----
====


=== vfwnmacc.vf
Mnemonic::
--
	vfwnmacc.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3d, attr: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-accumulate), overwrites addend, vd[i] = -(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmacc_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwnmacc_vf_intrinsic.cpp[]
----
====


=== vfwmsac.vv
Mnemonic::
--
	vfwmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3e, attr: 'funct6'},
]}
....

Description::
FP widening multiply-subtract-accumulator, overwrites addend, vd[i] = +(vs1[i] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmsac_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmsac_vv_intrinsic.cpp[]
----
====


=== vfwmsac.vf
Mnemonic::
--
	vfwmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3e, attr: 'funct6'},
]}
....

Description::
FP widening multiply-subtract-accumulator, overwrites addend, vd[i] = +(f[rs1] * vs2[i]) - vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwmsac_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwmsac_vf_intrinsic.cpp[]
----
====


=== vfwnmsac.vv
Mnemonic::
--
	vfwnmsac.vv vd, vs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3f, attr: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-subtract-accumulator), overwrites addend, vd[i] = -(vs1[i] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmsac_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwnmsac_vv_intrinsic.cpp[]
----
====


=== vfwnmsac.vf
Mnemonic::
--
	vfwnmsac.vf vd, rs1, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x3f, attr: 'funct6'},
]}
....

Description::
FP widening negate-(multiply-subtract-accumulator), overwrites addend, vd[i] = -(f[rs1] * vs2[i]) + vd[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwnmsac_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwnmsac_vf_intrinsic.cpp[]
----
====


=== Vector Floating-Point Square-Root Instruction



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfsqrt.v
Mnemonic::
--
	vfsqrt.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x0, attr: 'vfsqrt.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Floating-point square root, Vector-vector square root

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsqrt_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsqrt_v_intrinsic.cpp[]
----
====


=== Vector Floating-Point Reciprocal Square-Root Estimate Instruction



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfrsqrt7.v
Mnemonic::
--
	vfrsqrt7.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x4, attr: 'vfrsqrt7.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Floating-point reciprocal square-root estimate to 7 bits.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrsqrt7_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfrsqrt7_v_intrinsic.cpp[]
----
====


=== Vector Floating-Point Reciprocal Estimate Instruction



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfrec7.v
Mnemonic::
--
	vfrec7.v vd, vs2, vm
--

Description::
Floating-point reciprocal estimate to 7 bits.

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x5, attr: 'vfrec7.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfrec7_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfrec7_v_intrinsic.cpp[]
----
====


=== Vector Floating-Point MIN/MAX Instructions



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfmin.vv
Mnemonic::
--
	vfmin.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x04, attr: 'funct6'},
]}
....

Description::
Floating-point minimum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmin_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmin_vv_intrinsic.cpp[]
----
====


=== vfmin.vf
Mnemonic::
--
	vfmin.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x04, attr: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmin_vf.h[]

Description::
Floating-point minimum, vector-scalar

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmin_vf_intrinsic.cpp[]
----
====


=== vfmax.vv
Mnemonic::
--
	vfmax.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x06, attr: 'funct6'},
]}
....

Description::
Floating-point maximum, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmax_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmax_vv_intrinsic.cpp[]
----
====


=== vfmax.vf
Mnemonic::
--
	vfmax.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x06, attr: 'funct6'},
]}
....

Description::
Floating-point maximum, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmax_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmax_vf_intrinsic.cpp[]
----
====


=== Vector Floating-Point Sign-Injection Instructions



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfsgnj.vv
Mnemonic::
--
	vfsgnj.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnj_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnj_vv_intrinsic.cpp[]
----
====


=== vfsgnj.vf
Mnemonic::
--
	vfsgnj.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x08, attr: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnj_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnj_vf_intrinsic.cpp[]
----
====


=== vfsgnjn.vv
Mnemonic::
--
	vfsgnjn.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjn_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnjn_vv_intrinsic.cpp[]
----
====


=== vfsgnjn.vf
Mnemonic::
--
	vfsgnjn.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x09, attr: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjn_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnjn_vf_intrinsic.cpp[]
----
====


=== vfsgnjx.vv
Mnemonic::
--
	vfsgnjx.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjx_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnjx_vv_intrinsic.cpp[]
----
====


=== vfsgnjx.vf
Mnemonic::
--
	vfsgnjx.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x0a, attr: 'funct6'},
]}
....

Description::
vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfsgnjx_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfsgnjx_vf_intrinsic.cpp[]
----
====


=== Vector Floating-Point Compare Instructions



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vmfeq.vv
Mnemonic::
--
	vmfeq.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x18, attr: 'funct6'},
]}
....

Description::
Compare equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfeq_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfeq_vv_intrinsic.cpp[]
----
====


=== vmfeq.vf
Mnemonic::
--
	vmfeq.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x18, attr: 'funct6'},
]}
....

Description::
Compare equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmeq_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfeq_vf_intrinsic.cpp[]
----
====


=== vmfne.vv
Mnemonic::
--
	vmfne.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1c, attr: 'funct6'},
]}
....

Description::
Compare not equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfne_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfne_vv_intrinsic.cpp[]
----
====


=== vmfne.vf
Mnemonic::
--
	vmfne.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1c, attr: 'funct6'},
]}
....

Description::
Compare not equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfne_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfne_vf_intrinsic.cpp[]
----
====


=== vmflt.vv
Mnemonic::
--
	vmflt.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1b, attr: 'funct6'},
]}
....

Description::
Compare less than, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmflt_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmflt_vv_intrinsic.cpp[]
----
====


=== vmflt.vf
Mnemonic::
--
	vmflt.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1b, attr: 'funct6'},
]}
....

Description::
Compare less than, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmflt_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmflt_vf_intrinsic.cpp[]
----
====


=== vmfle.vv
Mnemonic::
--
	vmfle.vv vd, vs2, vs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 'vs1', type: 2},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x19, attr: 'funct6'},
]}
....

Description::
Compare less than or equal, Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfle_vv.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfle_vv_intrinsic.cpp[]
----
====


=== vmfle.vf
Mnemonic::
--
	vmfle.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x19, attr: 'funct6'},
]}
....

Description::
Compare less than or equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfle_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfle_vf_intrinsic.cpp[]
----
====


=== vmfgt.vf
Mnemonic::
--
	vmfgt.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1d, attr: 'funct6'},
]}
....

Description::
Compare greater than, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfgt_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfgt_vf_intrinsic.cpp[]
----
====


=== vmfge.vf
Mnemonic::
--
	vmfge.vf vd, vs2, rs1, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x1d, attr: 'funct6'},
]}
....

Description::
Compare greater than or equal, vector-scalar

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vmfge_vf.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vmfge_vf_intrinsic.cpp[]
----
====


=== Vector Floating-Point Classify Instruction



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfclass.v
Mnemonic::
--
	vfclass.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x10, attr: 'vfclass.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x13, attr: 'funct6'},
]}
....

Description::
Vector-vector

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfclass_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfclass_v_intrinsic.cpp[]
----
====


=== Vector Floating-Point Merge Instruction



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfmerge.vfm
Mnemonic::
--
	vfmerge.vfm vd, vs2, rs1, v0
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 0, attr: 'vm'},
  {bits: 6, name: 0x17, attr: 'funct6'},
]}
....

Description::
vd[i] = v0.mask[i] ? f[rs1] : vs2[i]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmerge_vfm.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmerge_vfm_intrinsic.cpp[]
----
====


=== Vector Floating-Point Move Instruction

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Vector_intrinsic.cpp[]
----
====


=== vfmv.v.f
Mnemonic::
--
	vfmv.v.f vd, rs1
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVF'},
  {bits: 5, name: 'vd', type: 2},
  {bits: 3, name: 5},
  {bits: 5, name: 'rs1', type: 4},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 1, attr: 'vm'},
  {bits: 6, name: 0x17, attr: 'funct6'},
]}
....

Description::
vd[i] = f[rs1]

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfmv_v_f.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfmv_v_f_intrinsic.cpp[]
----
====


=== Single-Width Floating-Point/Integer Type-Convert Instructions

=== vfcvt.xu.f.v
Mnemonic::
--
	vfcvt.xu.f.v     vd, vs2, vm
--

Description::
Convert float to unsigned integer.

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x0, attr: 'vfcvt.xu.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_xu_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_xu_f_v_intrinsic.cpp[]
----
====


=== vfcvt.x.f.v
Mnemonic::
--
	vfcvt.x.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x0, attr: 'vfcvt.x.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_x_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_x_f_v_intrinsic.cpp[]
----
====


=== vfcvt.rtz.xu.f.v
Mnemonic::
--
	vfcvt.rtz.xu.f.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x6, attr: 'vfcvt.rtz.xu.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_rtz_xu_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_rtz_xu_f_v_intrinsic.cpp[]
----
====


=== vfcvt.rtz.x.f.v
Mnemonic::
--
	vfcvt.rtz.x.f.v  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x7, attr: 'vfcvt.rtz.x.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_rtz_x_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_rtz_x_f_v_intrinsic.cpp[]
----
====


=== vfcvt.f.xu.v
Mnemonic::
--
	vfcvt.f.xu.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x2, attr: 'vfcvt.f.xu.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert unsigned integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_f_xu_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_f_xu_v_intrinsic.cpp[]
----
====


=== vfcvt.f.x.v
Mnemonic::
--
	vfcvt.f.x.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x3, attr: 'vfcvt.f.x.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert signed integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfcvt_f_x_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfcvt_f_x_v_intrinsic.cpp[]
----
====


=== Widening Floating-Point/Integer Type-Convert Instructions

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Widening_intrinsic.cpp[]
----
====


=== vfwcvt.xu.f.v
Mnemonic::
--
	vfwcvt.xu.f.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x8, attr: 'vfwcvt.xu.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to double-width unsigned integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_xu_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_xu_f_v_intrinsic.cpp[]
----
====


=== vfwcvt.x.f.v
Mnemonic::
--
	vfwcvt.x.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x9, attr: 'vfwcvt.x.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to double-width signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_x_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_x_f_v_intrinsic.cpp[]
----
====


=== vfwcvt.rtz.xu.f.v
Mnemonic::
--
	vfwcvt.rtz.xu.f.v vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0xe, attr: 'vfwcvt.rtz.xu.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to double-width unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_rtz_xu_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_rtz_xu_f_v_intrinsic.cpp[]
----
====


=== vfwcvt.rtz.x.f.v
Mnemonic::
--
	vfwcvt.rtz.x.f.v  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0xf, attr: 'vfwcvt.rtz.x.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert float to double-width signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_rtz_x_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_rtz_x_f_v_intrinsic.cpp[]
----
====


=== vfwcvt.f.xu.v
Mnemonic::
--
	vfwcvt.f.xu.v     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0xa, attr: 'vfwcvt.f.xu.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert unsigned integer to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_xu_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_f_xu_v_intrinsic.cpp[]
----
====


=== vfwcvt.f.x.v
Mnemonic::
--
	vfwcvt.f.x.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0xb, attr: 'vfwcvt.f.x.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert signed integer to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_x_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_f_x_v_intrinsic.cpp[]
----
====


=== vfwcvt.f.f.v
Mnemonic::
--
	vfwcvt.f.f.v      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0xc, attr: 'vfwcvt.f.f.v'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert single-width float to double-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfwcvt_f_f_v.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfwcvt_f_f_v_intrinsic.cpp[]
----
====


=== Narrowing Floating-Point/Integer Type-Convert Instructions



Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/Narrowing_intrinsic.cpp[]
----
====


=== vfncvt.xu.f.w
Mnemonic::
--
	vfncvt.xu.f.w     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x10, attr: 'vfncvt.xu.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to unsigned integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_xu_f_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_xu_f_w_intrinsic.cpp[]
----
====


=== vfncvt.x.f.w
Mnemonic::
--
	vfncvt.x.f.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x11, attr: 'vfncvt.x.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to signed integer.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_x_f_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_x_f_w_intrinsic.cpp[]
----
====


=== vfncvt.rtz.xu.f.w
Mnemonic::
--
	vfncvt.rtz.xu.f.w vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x16, attr: 'vfncvt.rtz.xu.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to unsigned integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rtz_xu_f_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_rtz_xu_f_w_intrinsic.cpp[]
----
====


=== vfncvt.rtz.x.f.w
Mnemonic::
--
	vfncvt.rtz.x.f.w  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x17, attr: 'vfncvt.rtz.x.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to signed integer, truncating.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rtz_x_f_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_rtz_x_f_w_intrinsic.cpp[]
----
====


=== vfncvt.f.xu.w
Mnemonic::
--
	vfncvt.f.xu.w     vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x12, attr: 'vfncvt.f.xu.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width unsigned integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_xu_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_f_xu_w_intrinsic.cpp[]
----
====


=== vfncvt.f.x.w
Mnemonic::
--
	vfncvt.f.x.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x13, attr: 'vfncvt.f.x.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width signed integer to float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_x_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_f_x_w_intrinsic.cpp[]
----
====


=== vfncvt.f.f.w
Mnemonic::
--
	vfncvt.f.f.w      vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x14, attr: 'vfncvt.f.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to single-width float.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_f_f_w.h[]

Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_f_f_w_intrinsic.cpp[]
----
====


=== vfncvt.rod.f.f.w
Mnemonic::
--
	vfncvt.rod.f.f.w  vd, vs2, vm
--

Encoding::
[wavedrom, , svg]
....
{reg: [
  {bits: 7, name: 0x57, attr: 'OPFVV'},
  {bits: 5, name: 'vd / rd', type: 7},
  {bits: 3, name: 1},
  {bits: 5, name: 0x15, attr: 'vfncvt.rod.f.f.w'},
  {bits: 5, name: 'vs2', type: 2},
  {bits: 1, name: 'vm'},
  {bits: 6, name: 0x12, attr: 'funct6'},
]}
....

Description::
Convert double-width float to single-width float, rounding towards odd.

Spike Implementation::
https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vfncvt_rod_f_f_w.h[]


Intrinsic Functions::
[%collapsible]
====
[source,c]
----
include::./intrinsic/vfncvt_rod_f_f_w_intrinsic.cpp[]
----
====
