vuint8mf8_t __riscv_vfncvt_xu_f_w_u8mf8 (vfloat16mf4_t src, size_t vl);
vuint8mf4_t __riscv_vfncvt_xu_f_w_u8mf4 (vfloat16mf2_t src, size_t vl);
vuint8mf2_t __riscv_vfncvt_xu_f_w_u8mf2 (vfloat16m1_t src, size_t vl);
vuint8m1_t __riscv_vfncvt_xu_f_w_u8m1 (vfloat16m2_t src, size_t vl);
vuint8m2_t __riscv_vfncvt_xu_f_w_u8m2 (vfloat16m4_t src, size_t vl);
vuint8m4_t __riscv_vfncvt_xu_f_w_u8m4 (vfloat16m8_t src, size_t vl);
vuint16mf4_t __riscv_vfncvt_xu_f_w_u16mf4 (vfloat32mf2_t src, size_t vl);
vuint16mf2_t __riscv_vfncvt_xu_f_w_u16mf2 (vfloat32m1_t src, size_t vl);
vuint16m1_t __riscv_vfncvt_xu_f_w_u16m1 (vfloat32m2_t src, size_t vl);
vuint16m2_t __riscv_vfncvt_xu_f_w_u16m2 (vfloat32m4_t src, size_t vl);
vuint16m4_t __riscv_vfncvt_xu_f_w_u16m4 (vfloat32m8_t src, size_t vl);
vuint32mf2_t __riscv_vfncvt_xu_f_w_u32mf2 (vfloat64m1_t src, size_t vl);
vuint32m1_t __riscv_vfncvt_xu_f_w_u32m1 (vfloat64m2_t src, size_t vl);
vuint32m2_t __riscv_vfncvt_xu_f_w_u32m2 (vfloat64m4_t src, size_t vl);
vuint32m4_t __riscv_vfncvt_xu_f_w_u32m4 (vfloat64m8_t src, size_t vl);
vuint8mf8_t __riscv_vfncvt_xu_f_w_u8mf8_m (vbool64_t mask, vfloat16mf4_t src, size_t vl);
vuint8mf4_t __riscv_vfncvt_xu_f_w_u8mf4_m (vbool32_t mask, vfloat16mf2_t src, size_t vl);
vuint8mf2_t __riscv_vfncvt_xu_f_w_u8mf2_m (vbool16_t mask, vfloat16m1_t src, size_t vl);
vuint8m1_t __riscv_vfncvt_xu_f_w_u8m1_m (vbool8_t mask, vfloat16m2_t src, size_t vl);
vuint8m2_t __riscv_vfncvt_xu_f_w_u8m2_m (vbool4_t mask, vfloat16m4_t src, size_t vl);
vuint8m4_t __riscv_vfncvt_xu_f_w_u8m4_m (vbool2_t mask, vfloat16m8_t src, size_t vl);
vuint16mf4_t __riscv_vfncvt_xu_f_w_u16mf4_m (vbool64_t mask, vfloat32mf2_t src, size_t vl);
vuint16mf2_t __riscv_vfncvt_xu_f_w_u16mf2_m (vbool32_t mask, vfloat32m1_t src, size_t vl);
vuint16m1_t __riscv_vfncvt_xu_f_w_u16m1_m (vbool16_t mask, vfloat32m2_t src, size_t vl);
vuint16m2_t __riscv_vfncvt_xu_f_w_u16m2_m (vbool8_t mask, vfloat32m4_t src, size_t vl);
vuint16m4_t __riscv_vfncvt_xu_f_w_u16m4_m (vbool4_t mask, vfloat32m8_t src, size_t vl);
vuint32mf2_t __riscv_vfncvt_xu_f_w_u32mf2_m (vbool64_t mask, vfloat64m1_t src, size_t vl);
vuint32m1_t __riscv_vfncvt_xu_f_w_u32m1_m (vbool32_t mask, vfloat64m2_t src, size_t vl);
vuint32m2_t __riscv_vfncvt_xu_f_w_u32m2_m (vbool16_t mask, vfloat64m4_t src, size_t vl);
vuint32m4_t __riscv_vfncvt_xu_f_w_u32m4_m (vbool8_t mask, vfloat64m8_t src, size_t vl);
vuint8mf8_t __riscv_vfncvt_xu_f_w_u8mf8_rm (vfloat16mf4_t src, unsigned int frm, size_t vl);
vuint8mf4_t __riscv_vfncvt_xu_f_w_u8mf4_rm (vfloat16mf2_t src, unsigned int frm, size_t vl);
vuint8mf2_t __riscv_vfncvt_xu_f_w_u8mf2_rm (vfloat16m1_t src, unsigned int frm, size_t vl);
vuint8m1_t __riscv_vfncvt_xu_f_w_u8m1_rm (vfloat16m2_t src, unsigned int frm, size_t vl);
vuint8m2_t __riscv_vfncvt_xu_f_w_u8m2_rm (vfloat16m4_t src, unsigned int frm, size_t vl);
vuint8m4_t __riscv_vfncvt_xu_f_w_u8m4_rm (vfloat16m8_t src, unsigned int frm, size_t vl);
vuint16mf4_t __riscv_vfncvt_xu_f_w_u16mf4_rm (vfloat32mf2_t src, unsigned int frm, size_t vl);
vuint16mf2_t __riscv_vfncvt_xu_f_w_u16mf2_rm (vfloat32m1_t src, unsigned int frm, size_t vl);
vuint16m1_t __riscv_vfncvt_xu_f_w_u16m1_rm (vfloat32m2_t src, unsigned int frm, size_t vl);
vuint16m2_t __riscv_vfncvt_xu_f_w_u16m2_rm (vfloat32m4_t src, unsigned int frm, size_t vl);
vuint16m4_t __riscv_vfncvt_xu_f_w_u16m4_rm (vfloat32m8_t src, unsigned int frm, size_t vl);
vuint32mf2_t __riscv_vfncvt_xu_f_w_u32mf2_rm (vfloat64m1_t src, unsigned int frm, size_t vl);
vuint32m1_t __riscv_vfncvt_xu_f_w_u32m1_rm (vfloat64m2_t src, unsigned int frm, size_t vl);
vuint32m2_t __riscv_vfncvt_xu_f_w_u32m2_rm (vfloat64m4_t src, unsigned int frm, size_t vl);
vuint32m4_t __riscv_vfncvt_xu_f_w_u32m4_rm (vfloat64m8_t src, unsigned int frm, size_t vl);
vuint8mf8_t __riscv_vfncvt_xu_f_w_u8mf8_rm_m (vbool64_t mask, vfloat16mf4_t src, unsigned int frm, size_t vl);
vuint8mf4_t __riscv_vfncvt_xu_f_w_u8mf4_rm_m (vbool32_t mask, vfloat16mf2_t src, unsigned int frm, size_t vl);
vuint8mf2_t __riscv_vfncvt_xu_f_w_u8mf2_rm_m (vbool16_t mask, vfloat16m1_t src, unsigned int frm, size_t vl);
vuint8m1_t __riscv_vfncvt_xu_f_w_u8m1_rm_m (vbool8_t mask, vfloat16m2_t src, unsigned int frm, size_t vl);
vuint8m2_t __riscv_vfncvt_xu_f_w_u8m2_rm_m (vbool4_t mask, vfloat16m4_t src, unsigned int frm, size_t vl);
vuint8m4_t __riscv_vfncvt_xu_f_w_u8m4_rm_m (vbool2_t mask, vfloat16m8_t src, unsigned int frm, size_t vl);
vuint16mf4_t __riscv_vfncvt_xu_f_w_u16mf4_rm_m (vbool64_t mask, vfloat32mf2_t src, unsigned int frm, size_t vl);
vuint16mf2_t __riscv_vfncvt_xu_f_w_u16mf2_rm_m (vbool32_t mask, vfloat32m1_t src, unsigned int frm, size_t vl);
vuint16m1_t __riscv_vfncvt_xu_f_w_u16m1_rm_m (vbool16_t mask, vfloat32m2_t src, unsigned int frm, size_t vl);
vuint16m2_t __riscv_vfncvt_xu_f_w_u16m2_rm_m (vbool8_t mask, vfloat32m4_t src, unsigned int frm, size_t vl);
vuint16m4_t __riscv_vfncvt_xu_f_w_u16m4_rm_m (vbool4_t mask, vfloat32m8_t src, unsigned int frm, size_t vl);
vuint32mf2_t __riscv_vfncvt_xu_f_w_u32mf2_rm_m (vbool64_t mask, vfloat64m1_t src, unsigned int frm, size_t vl);
vuint32m1_t __riscv_vfncvt_xu_f_w_u32m1_rm_m (vbool32_t mask, vfloat64m2_t src, unsigned int frm, size_t vl);
vuint32m2_t __riscv_vfncvt_xu_f_w_u32m2_rm_m (vbool16_t mask, vfloat64m4_t src, unsigned int frm, size_t vl);
vuint32m4_t __riscv_vfncvt_xu_f_w_u32m4_rm_m (vbool8_t mask, vfloat64m8_t src, unsigned int frm, size_t vl);
