vint8mf8x2_t __riscv_vlsseg2e8_v_i8mf8x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x3_t __riscv_vlsseg3e8_v_i8mf8x3 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x4_t __riscv_vlsseg4e8_v_i8mf8x4 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x5_t __riscv_vlsseg5e8_v_i8mf8x5 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x6_t __riscv_vlsseg6e8_v_i8mf8x6 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x7_t __riscv_vlsseg7e8_v_i8mf8x7 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x8_t __riscv_vlsseg8e8_v_i8mf8x8 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x2_t __riscv_vlsseg2e8_v_i8mf4x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x3_t __riscv_vlsseg3e8_v_i8mf4x3 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x4_t __riscv_vlsseg4e8_v_i8mf4x4 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x5_t __riscv_vlsseg5e8_v_i8mf4x5 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x6_t __riscv_vlsseg6e8_v_i8mf4x6 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x7_t __riscv_vlsseg7e8_v_i8mf4x7 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x8_t __riscv_vlsseg8e8_v_i8mf4x8 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x2_t __riscv_vlsseg2e8_v_i8mf2x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x3_t __riscv_vlsseg3e8_v_i8mf2x3 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x4_t __riscv_vlsseg4e8_v_i8mf2x4 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x5_t __riscv_vlsseg5e8_v_i8mf2x5 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x6_t __riscv_vlsseg6e8_v_i8mf2x6 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x7_t __riscv_vlsseg7e8_v_i8mf2x7 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x8_t __riscv_vlsseg8e8_v_i8mf2x8 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x2_t __riscv_vlsseg2e8_v_i8m1x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x3_t __riscv_vlsseg3e8_v_i8m1x3 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x4_t __riscv_vlsseg4e8_v_i8m1x4 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x5_t __riscv_vlsseg5e8_v_i8m1x5 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x6_t __riscv_vlsseg6e8_v_i8m1x6 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x7_t __riscv_vlsseg7e8_v_i8m1x7 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x8_t __riscv_vlsseg8e8_v_i8m1x8 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x2_t __riscv_vlsseg2e8_v_i8m2x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x3_t __riscv_vlsseg3e8_v_i8m2x3 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x4_t __riscv_vlsseg4e8_v_i8m2x4 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m4x2_t __riscv_vlsseg2e8_v_i8m4x2 (const int8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x2_t __riscv_vlsseg2e8_v_u8mf8x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x3_t __riscv_vlsseg3e8_v_u8mf8x3 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x4_t __riscv_vlsseg4e8_v_u8mf8x4 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x5_t __riscv_vlsseg5e8_v_u8mf8x5 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x6_t __riscv_vlsseg6e8_v_u8mf8x6 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x7_t __riscv_vlsseg7e8_v_u8mf8x7 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x8_t __riscv_vlsseg8e8_v_u8mf8x8 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x2_t __riscv_vlsseg2e8_v_u8mf4x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x3_t __riscv_vlsseg3e8_v_u8mf4x3 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x4_t __riscv_vlsseg4e8_v_u8mf4x4 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x5_t __riscv_vlsseg5e8_v_u8mf4x5 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x6_t __riscv_vlsseg6e8_v_u8mf4x6 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x7_t __riscv_vlsseg7e8_v_u8mf4x7 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x8_t __riscv_vlsseg8e8_v_u8mf4x8 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x2_t __riscv_vlsseg2e8_v_u8mf2x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x3_t __riscv_vlsseg3e8_v_u8mf2x3 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x4_t __riscv_vlsseg4e8_v_u8mf2x4 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x5_t __riscv_vlsseg5e8_v_u8mf2x5 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x6_t __riscv_vlsseg6e8_v_u8mf2x6 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x7_t __riscv_vlsseg7e8_v_u8mf2x7 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x8_t __riscv_vlsseg8e8_v_u8mf2x8 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x2_t __riscv_vlsseg2e8_v_u8m1x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x3_t __riscv_vlsseg3e8_v_u8m1x3 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x4_t __riscv_vlsseg4e8_v_u8m1x4 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x5_t __riscv_vlsseg5e8_v_u8m1x5 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x6_t __riscv_vlsseg6e8_v_u8m1x6 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x7_t __riscv_vlsseg7e8_v_u8m1x7 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x8_t __riscv_vlsseg8e8_v_u8m1x8 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x2_t __riscv_vlsseg2e8_v_u8m2x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x3_t __riscv_vlsseg3e8_v_u8m2x3 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x4_t __riscv_vlsseg4e8_v_u8m2x4 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m4x2_t __riscv_vlsseg2e8_v_u8m4x2 (const uint8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x2_t __riscv_vlsseg2e8_v_i8mf8x2_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x3_t __riscv_vlsseg3e8_v_i8mf8x3_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x4_t __riscv_vlsseg4e8_v_i8mf8x4_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x5_t __riscv_vlsseg5e8_v_i8mf8x5_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x6_t __riscv_vlsseg6e8_v_i8mf8x6_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x7_t __riscv_vlsseg7e8_v_i8mf8x7_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf8x8_t __riscv_vlsseg8e8_v_i8mf8x8_m (vbool64_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x2_t __riscv_vlsseg2e8_v_i8mf4x2_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x3_t __riscv_vlsseg3e8_v_i8mf4x3_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x4_t __riscv_vlsseg4e8_v_i8mf4x4_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x5_t __riscv_vlsseg5e8_v_i8mf4x5_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x6_t __riscv_vlsseg6e8_v_i8mf4x6_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x7_t __riscv_vlsseg7e8_v_i8mf4x7_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf4x8_t __riscv_vlsseg8e8_v_i8mf4x8_m (vbool32_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x2_t __riscv_vlsseg2e8_v_i8mf2x2_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x3_t __riscv_vlsseg3e8_v_i8mf2x3_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x4_t __riscv_vlsseg4e8_v_i8mf2x4_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x5_t __riscv_vlsseg5e8_v_i8mf2x5_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x6_t __riscv_vlsseg6e8_v_i8mf2x6_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x7_t __riscv_vlsseg7e8_v_i8mf2x7_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8mf2x8_t __riscv_vlsseg8e8_v_i8mf2x8_m (vbool16_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x2_t __riscv_vlsseg2e8_v_i8m1x2_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x3_t __riscv_vlsseg3e8_v_i8m1x3_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x4_t __riscv_vlsseg4e8_v_i8m1x4_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x5_t __riscv_vlsseg5e8_v_i8m1x5_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x6_t __riscv_vlsseg6e8_v_i8m1x6_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x7_t __riscv_vlsseg7e8_v_i8m1x7_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m1x8_t __riscv_vlsseg8e8_v_i8m1x8_m (vbool8_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x2_t __riscv_vlsseg2e8_v_i8m2x2_m (vbool4_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x3_t __riscv_vlsseg3e8_v_i8m2x3_m (vbool4_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m2x4_t __riscv_vlsseg4e8_v_i8m2x4_m (vbool4_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vint8m4x2_t __riscv_vlsseg2e8_v_i8m4x2_m (vbool2_t mask, const int8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x2_t __riscv_vlsseg2e8_v_u8mf8x2_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x3_t __riscv_vlsseg3e8_v_u8mf8x3_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x4_t __riscv_vlsseg4e8_v_u8mf8x4_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x5_t __riscv_vlsseg5e8_v_u8mf8x5_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x6_t __riscv_vlsseg6e8_v_u8mf8x6_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x7_t __riscv_vlsseg7e8_v_u8mf8x7_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf8x8_t __riscv_vlsseg8e8_v_u8mf8x8_m (vbool64_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x2_t __riscv_vlsseg2e8_v_u8mf4x2_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x3_t __riscv_vlsseg3e8_v_u8mf4x3_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x4_t __riscv_vlsseg4e8_v_u8mf4x4_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x5_t __riscv_vlsseg5e8_v_u8mf4x5_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x6_t __riscv_vlsseg6e8_v_u8mf4x6_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x7_t __riscv_vlsseg7e8_v_u8mf4x7_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf4x8_t __riscv_vlsseg8e8_v_u8mf4x8_m (vbool32_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x2_t __riscv_vlsseg2e8_v_u8mf2x2_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x3_t __riscv_vlsseg3e8_v_u8mf2x3_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x4_t __riscv_vlsseg4e8_v_u8mf2x4_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x5_t __riscv_vlsseg5e8_v_u8mf2x5_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x6_t __riscv_vlsseg6e8_v_u8mf2x6_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x7_t __riscv_vlsseg7e8_v_u8mf2x7_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8mf2x8_t __riscv_vlsseg8e8_v_u8mf2x8_m (vbool16_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x2_t __riscv_vlsseg2e8_v_u8m1x2_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x3_t __riscv_vlsseg3e8_v_u8m1x3_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x4_t __riscv_vlsseg4e8_v_u8m1x4_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x5_t __riscv_vlsseg5e8_v_u8m1x5_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x6_t __riscv_vlsseg6e8_v_u8m1x6_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x7_t __riscv_vlsseg7e8_v_u8m1x7_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m1x8_t __riscv_vlsseg8e8_v_u8m1x8_m (vbool8_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x2_t __riscv_vlsseg2e8_v_u8m2x2_m (vbool4_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x3_t __riscv_vlsseg3e8_v_u8m2x3_m (vbool4_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m2x4_t __riscv_vlsseg4e8_v_u8m2x4_m (vbool4_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
vuint8m4x2_t __riscv_vlsseg2e8_v_u8m4x2_m (vbool2_t mask, const uint8_t *base, ptrdiff_t bstride, size_t vl);
